# Generated by Django 4.2.16 on 2024-10-19 16:35

import utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('authors', models.TextField(blank=True, null=True)),
                ('link', models.URLField(blank=True, null=True)),
                ('resource_file', utils.fields.CustomFileField(
                    blank=True, default='uploads/default_file.txt', null=True, upload_to='uploads/files/')),
                ('link_title', models.CharField(blank=True,
                 default='Read More', max_length=100, null=True)),
                ('category', models.CharField(blank=True, choices=[('research', 'Research'), ('technical', 'Technical'), (
                    'policy', 'Policy'), ('guide', 'Guide'), ('manual', 'Manual')], default='research', max_length=40, null=True)),
                ('order', models.IntegerField(default=1)),
            ],
            options={
                'ordering': ['order', '-id'],
            },
        ),
    ]
