# Generated by Django 5.1.4 on 2024-12-06 17:27

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0010_alter_publication_resource_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='resource_file',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True),
        ),
    ]
