# Generated by Django 4.2.5 on 2024-11-26 12:18

from django.db import migrations
import utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0011_publication_created_publication_is_deleted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='resource_file',
            field=utils.fields.CustomFileField(blank=True, default='uploads/default_file.txt', null=True, upload_to='uploads/files/'),
        ),
    ]
