# Generated by Django 5.1.4 on 2025-05-22 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0011_alter_publication_resource_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='description',
            field=models.TextField(blank=True, help_text='Optional description of the publication', null=True),
        ),
    ]
