const mongoose = require("mongoose");

const envs = {
  SESSION_SECRET: process.env.SESSION_SECRET,
  TS_TEST_CHANNEL: process.env.TS_TEST_CHANNEL,
  TS_API_KEY_TEST_DEVICE: process.env.TS_API_KEY_TEST_DEVICE,
  GET_CHANNELS_CACHE_EXPIRATION: process.env.GET_CHANNELS_CACHE_EXPIRATION,
  GET_LAST_ENTRY_CACHE_EXPIRATION: process.env.GET_LAST_ENTRY_CACHE_EXPIRATION,
  GET_HOURLY_CACHE_EXPIRATION: process.env.GET_HOURLY_CACHE_EXPIRATION,
  GET_DESCRPIPTIVE_LAST_ENTRY_CACHE_EXPIRATION:
    process.env.DESCRPIPTIVE_LAST_ENTRY_CACHE_EXPIRATION,
  GET_CHANNEL_LAST_ENTRY_AGE_CACHE_EXPIRATION:
    process.env.CHANNEL_LAST_ENTRY_AGE_CACHE_EXPIRATION,
  GET_LAST_FIELD_ENTRY_AGE_CACHE_EXPIRATION:
    process.env.LAST_FIELD_ENTRY_AGE_CACHE_EXPIRATION,
  GET_DEVICE_COUNT_CACHE_EXPIRATION: process.env.DEVICE_COUNT_CACHE_EXPIRATION,
  DEFAULT_TENANT: process.env.DEFAULT_TENANT,
};
module.exports = envs;
