nameOverride: ''
fullnameOverride: ''
images:
  repositories:
    api: airqoacr.azurecr.io/airqo-stage-analytics-api
  tag: stage-2080d6a5-1787147353
externalSecret:
  enabled: true
api:
  name: airqo-stage-analytics-api
  label: analytics-api
  secret: sta-env-analytics
  replicaCount: 2
  podAnnotations: {}
  resources:
    common:
      limits:
        cpu: 200m
        memory: 1000Mi
      requests:
        cpu: 10m
        memory: 250Mi
volumeMounts:
  - name: config-volume
    mountPath: /etc/config
volumes:
  - name: config-volume
    configMap:
      name: stage-analytics-config-files
service:
  type: NodePort
  ports:
    - name: analytics-api
      port: 5000
      protocol: TCP
      targetPort: 5000
      nodePort: 31003
ingress:
  enabled: false
autoscaling:
  minReplicas: 1
  maxReplicas: 2
  targetMemoryUtilizationPercentage: 85
