# Generated by Django 5.1.4 on 2024-12-06 16:24

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0006_alter_boardmember_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardmember',
            name='picture',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True),
        ),
    ]
