# Generated by Django 4.2.5 on 2024-11-26 12:18

from django.db import migrations
import utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0007_boardmember_created_boardmember_is_deleted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardmember',
            name='picture',
            field=utils.fields.CustomImageField(blank=True, default='uploads/default_image.webp', null=True, upload_to='uploads/images/', validators=[utils.fields.validate_image_format]),
        ),
    ]
