apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: prod-env-superset
  namespace: superset
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: azure-kv-store
    kind: ClusterSecretStore
  target:
    name: prod-env-superset
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: prod-env-superset
        version: latest
