apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.app.k8sSecret }}
  labels:
    {{- include "airqo-beacon-api.labels" . | nindent 4 }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: azure-kv-store   # your existing ClusterSecretStore
    kind: ClusterSecretStore
  target:
    name: {{ .Values.app.k8sSecret }}
    creationPolicy: Owner
    deletionPolicy: Retain
  dataFrom:
    - extract:
        key: {{ .Values.app.azureSecret }} # key in external store
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
