# Generated by Django 4.2.16 on 2024-10-19 14:40

import utils.fields
from django.db import migrations, models
import django.db.models.deletion
import django_quill.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('title_subtext', models.CharField(max_length=90)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('registration_link', models.URLField(blank=True, null=True)),
                ('website_category', models.CharField(blank=True, choices=[
                 ('airqo', 'AirQo'), ('cleanair', 'CleanAir')], default='airqo', max_length=40, null=True)),
                ('event_tag', models.CharField(blank=True, choices=[
                 ('none', 'None'), ('featured', 'Featured')], default='none', max_length=40, null=True)),
                ('event_category', models.CharField(blank=True, choices=[('none', 'None'), ('webinar', 'Webinar'), ('workshop', 'Workshop'), ('marathon', 'Marathon'), ('conference', 'Conference'), (
                    'summit', 'Summit'), ('commemoration', 'Commemoration'), ('in-person', 'In-person'), ('hybrid', 'Hybrid')], default='none', max_length=40, null=True)),
                ('event_image', utils.fields.CustomImageField(
                    blank=True, default='uploads/default_image.webp', null=True, upload_to='uploads/images/')),
                ('background_image', utils.fields.CustomImageField(
                    blank=True, default='uploads/default_image.webp', null=True, upload_to='uploads/images/')),
                ('location_name', models.CharField(
                    blank=True, max_length=100, null=True)),
                ('location_link', models.URLField(blank=True, null=True)),
                ('event_details', django_quill.fields.QuillField(
                    default='No details available yet.')),
                ('order', models.IntegerField(default=1)),
            ],
            options={
                'ordering': ['order', '-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('program_details', django_quill.fields.QuillField(
                    default='No details available yet.')),
                ('order', models.IntegerField(default=1)),
                ('event', models.ForeignKey(blank=True, null=True,
                 on_delete=django.db.models.deletion.SET_NULL, related_name='programs', to='event.event')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('venue', models.CharField(blank=True, max_length=80, null=True)),
                ('session_title', models.CharField(max_length=150)),
                ('session_details', django_quill.fields.QuillField(
                    default='No details available yet.')),
                ('order', models.IntegerField(default=1)),
                ('program', models.ForeignKey(blank=True, null=True,
                 on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='event.program')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('link', models.URLField(blank=True, null=True)),
                ('resource', utils.fields.CustomFileField(
                    blank=True, default='uploads/default_file.txt', null=True, upload_to='uploads/files/')),
                ('order', models.IntegerField(default=1)),
                ('event', models.ForeignKey(blank=True, null=True,
                 on_delete=django.db.models.deletion.SET_NULL, related_name='resources', to='event.event')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='PartnerLogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('partner_logo', utils.fields.CustomImageField(
                    blank=True, default='uploads/default_image.webp', null=True, upload_to='uploads/images/')),
                ('name', models.CharField(max_length=70)),
                ('order', models.IntegerField(default=1)),
                ('event', models.ForeignKey(blank=True, null=True,
                 on_delete=django.db.models.deletion.SET_NULL, related_name='partner_logos', to='event.event')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('inquiry', models.CharField(max_length=80)),
                ('role', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('order', models.IntegerField(default=1)),
                ('event', models.ForeignKey(blank=True, null=True,
                 on_delete=django.db.models.deletion.SET_NULL, related_name='inquiries', to='event.event')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
