# Generated by Django 4.2.5 on 2024-11-25 23:14

import datetime
from django.db import migrations, models
import utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0008_alter_event_background_image_alter_event_event_image_and_more'),
    ]

    operations = []
