# Generated by Django 5.1.4 on 2024-12-06 13:39

import django.core.validators
import utils.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0016_alter_event_background_image_alter_event_event_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='background_image',
            field=utils.fields.CustomCloudinaryField(blank=True, default='website/uploads/default_image.webp', max_length=255, null=True, validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp', 'gif', 'bmp', 'tiff']), utils.fields.validate_image_format, django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp', 'gif', 'bmp', 'tiff']), utils.fields.validate_image_format]),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_image',
            field=utils.fields.CustomCloudinaryField(blank=True, default='website/uploads/default_image.webp', max_length=255, null=True, validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp', 'gif', 'bmp', 'tiff']), utils.fields.validate_image_format, django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp', 'gif', 'bmp', 'tiff']), utils.fields.validate_image_format]),
        ),
        migrations.AlterField(
            model_name='partnerlogo',
            name='partner_logo',
            field=utils.fields.CustomCloudinaryField(blank=True, default='website/uploads/default_image.webp', max_length=255, null=True, validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp', 'gif', 'bmp', 'tiff']), utils.fields.validate_image_format, django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp', 'gif', 'bmp', 'tiff']), utils.fields.validate_image_format]),
        ),
        migrations.AlterField(
            model_name='resource',
            name='resource',
            field=utils.fields.CustomCloudinaryField(blank=True, default='website/uploads/default_image.webp', max_length=255, null=True, validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp', 'gif', 'bmp', 'tiff']), utils.fields.validate_image_format]),
        ),
    ]
