# Generated by Django 5.1.4 on 2025-09-09 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0018_alter_event_background_image_alter_event_event_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='slug',
            field=models.SlugField(blank=True, help_text='URL-friendly identifier', max_length=255, null=True, unique=True),
        ),
    ]
