# Generated by Django 5.1.4 on 2026-05-04 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0020_alter_event_order_alter_inquiry_order_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="event",
            index=models.Index(
                fields=["event_tag", "order", "start_date"],
                name="event_event_event_t_d53348_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(
                fields=["website_category", "order", "start_date"],
                name="event_event_website_f98a4a_idx",
            ),
        ),
    ]
