# Generated by Django 5.1.4 on 2026-05-04 09:32

import django_quill.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0021_event_event_event_event_t_d53348_idx_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="event_details",
            field=django_quill.fields.QuillField(default='{"delta":"","html":""}'),
        ),
        migrations.AlterField(
            model_name="program",
            name="program_details",
            field=django_quill.fields.QuillField(default='{"delta":"","html":""}'),
        ),
        migrations.AlterField(
            model_name="session",
            name="session_details",
            field=django_quill.fields.QuillField(default='{"delta":"","html":""}'),
        ),
    ]
