const mongoose = require("mongoose");
const prodConfig = {
  ADMIN_SETUP_SECRET: process.env.PROD_ADMIN_SETUP_SECRET,
  BYPASS_CAPTCHA: process.env.PROD_BYPASS_CAPTCHA === "true" || false,
  RECAPTCHA_SITE_KEY: process.env.PROD_RECAPTCHA_SITE_KEY,
  RECAPTCHA_SECRET_KEY: process.env.PROD_RECAPTCHA_SECRET_KEY,
  BYPASS_RATE_LIMIT: process.env.PROD_BYPASS_RATE_LIMIT === "true" || false,
  DEFAULT_AIRQLOUD: process.env.PROD_DEFAULT_AIRQLOUD,
  DEFAULT_GRID: process.env.PROD_DEFAULT_GRID,
  DEFAULT_GROUP: process.env.PROD_DEFAULT_GROUP,
  AIRQO_GROUP_ID: process.env.PROD_DEFAULT_GROUP,
  DEFAULT_GROUP_ROLE: process.env.PROD_DEFAULT_GROUP_ROLE,
  DEFAULT_NETWORK: process.env.PROD_DEFAULT_NETWORK,
  DEFAULT_NETWORK_ROLE: process.env.PROD_DEFAULT_NETWORK_ROLE,
  MONGO_URI: process.env.MONGO_PROD_URI,
  COMMAND_MONGO_URI: process.env.COMMAND_MONGO_PROD_URI,
  QUERY_MONGO_URI: process.env.QUERY_MONGO_PROD_URI,
  DB_NAME: process.env.MONGO_PROD || "auth_prod",
  PWD_RESET: `${process.env.ANALYTICS_PRODUCTION_BASE_URL}/reset`,
  LOGIN_PAGE: `${process.env.ANALYTICS_PRODUCTION_BASE_URL}/login`,
  FORGOT_PAGE: `${process.env.ANALYTICS_PRODUCTION_BASE_URL}/forgot`,
  PLATFORM_BASE_URL: process.env.ANALYTICS_PRODUCTION_BASE_URL,
  ANALYTICS_BASE_URL: "https://analytics.airqo.net",
  ENVIRONMENT: "PRODUCTION ENVIRONMENT",
  KAFKA_BOOTSTRAP_SERVERS: process.env.KAFKA_BOOTSTRAP_SERVERS_PROD
    ? process.env.KAFKA_BOOTSTRAP_SERVERS_PROD.split(",").filter(
        (value) => value.trim() !== ""
      )
    : [],
  KAFKA_TOPICS: process.env.KAFKA_TOPICS_PROD,
  SCHEMA_REGISTRY: process.env.SCHEMA_REGISTRY_PROD,
  KAFKA_RAW_MEASUREMENTS_TOPICS: process.env.KAFKA_RAW_MEASUREMENTS_TOPICS_PROD,
  KAFKA_CLIENT_ID: process.env.KAFKA_CLIENT_ID_PROD,
  KAFKA_CLIENT_GROUP: process.env.KAFKA_CLIENT_GROUP_PROD,
  REDIS_SERVER: process.env.PROD_REDIS_SERVER,
  REDIS_PORT: process.env.PROD_REDIS_PORT,
  SELECTED_SITES: process.env.SELECTED_SITES_PRODUCTION
    ? process.env.SELECTED_SITES_PRODUCTION.split(",").filter(
        (value) => value.trim() !== ""
      )
    : [],
  API_TOKEN: process.env.PROD_API_TOKEN,
  PADDLE_SUCCESS_REDIRECT_URL: process.env.PROD_PADDLE_SUCCESS_REDIRECT_URL,
  PADDLE_CANCEL_REDIRECT_URL: process.env.PROD_PADDLE_CANCEL_REDIRECT_URL,
  PADDLE_PUBLIC_KEY: process.env.PROD_PADDLE_PUBLIC_KEY,
  PADDLE_SECRET_KEY: process.env.PROD_PADDLE_SECRET_KEY,
  PADDLE_ENVIRONMENT: process.env.PROD_PADDLE_ENVIRONMENT,
  PADDLE_API_KEY: process.env.PROD_PADDLE_API_KEY,
  ONBOARDING_BASE_URL:
    process.env.PROD_ONBOARDING_BASE_URL ||
    "https://analytics.airqo.net/onboarding",
};
module.exports = prodConfig;
