const mongoose = require("mongoose");
const prodConfig = {
  ADMIN_SETUP_SECRET: process.env.PROD_ADMIN_SETUP_SECRET,
  BYPASS_CAPTCHA: process.env.PROD_BYPASS_CAPTCHA === "true" || false,
  RECAPTCHA_SITE_KEY: process.env.PROD_RECAPTCHA_SITE_KEY,
  RECAPTCHA_SECRET_KEY: process.env.PROD_RECAPTCHA_SECRET_KEY,
  BYPASS_RATE_LIMIT: process.env.PROD_BYPASS_RATE_LIMIT === "true" || false,
  DEFAULT_AIRQLOUD: process.env.PROD_DEFAULT_AIRQLOUD,
  DEFAULT_GRID: process.env.PROD_DEFAULT_GRID,
  DEFAULT_GROUP: process.env.PROD_DEFAULT_GROUP,
  AIRQO_GROUP_ID: process.env.PROD_DEFAULT_GROUP,
  DEFAULT_GROUP_ROLE: process.env.PROD_DEFAULT_GROUP_ROLE,
  DEFAULT_NETWORK: process.env.PROD_DEFAULT_NETWORK,
  DEFAULT_NETWORK_ROLE: process.env.PROD_DEFAULT_NETWORK_ROLE,
  MONGO_URI: process.env.MONGO_PROD_URI,
  COMMAND_MONGO_URI: process.env.COMMAND_MONGO_PROD_URI,
  QUERY_MONGO_URI: process.env.QUERY_MONGO_PROD_URI,
  DB_NAME: process.env.MONGO_PROD || "auth_prod",
  PWD_RESET: `${process.env.ANALYTICS_PRODUCTION_BASE_URL}/reset`,
  LOGIN_PAGE: `${process.env.ANALYTICS_PRODUCTION_BASE_URL}/user/login`,
  FORGOT_PAGE: `${process.env.ANALYTICS_PRODUCTION_BASE_URL}/forgot`,
  PLATFORM_BASE_URL: process.env.ANALYTICS_PRODUCTION_BASE_URL,
  ANALYTICS_BASE_URL: "https://analytics.airqo.net",
  ENVIRONMENT: "PRODUCTION ENVIRONMENT",
  KAFKA_BOOTSTRAP_SERVERS: process.env.KAFKA_BOOTSTRAP_SERVERS_PROD
    ? process.env.KAFKA_BOOTSTRAP_SERVERS_PROD.split(",").filter(
        (value) => value.trim() !== "",
      )
    : [],
  GROUPS_TOPIC: process.env.GROUPS_TOPIC_PROD || "groups-topic",
  KAFKA_TOPICS: process.env.KAFKA_TOPICS_PROD,
  SCHEMA_REGISTRY: process.env.SCHEMA_REGISTRY_PROD,
  KAFKA_RAW_MEASUREMENTS_TOPICS: process.env.KAFKA_RAW_MEASUREMENTS_TOPICS_PROD,
  KAFKA_CLIENT_ID: process.env.KAFKA_CLIENT_ID_PROD,
  KAFKA_CLIENT_GROUP: process.env.KAFKA_CLIENT_GROUP_PROD,
  REDIS_SERVER: process.env.PROD_REDIS_SERVER,
  REDIS_PORT: process.env.PROD_REDIS_PORT,
  SELECTED_SITES: process.env.SELECTED_SITES_PRODUCTION
    ? process.env.SELECTED_SITES_PRODUCTION.split(",").filter(
        (value) => value.trim() !== "",
      )
    : [],
  API_TOKEN: process.env.PROD_API_TOKEN,
  PADDLE_SUCCESS_REDIRECT_URL: process.env.PROD_PADDLE_SUCCESS_REDIRECT_URL,
  PADDLE_CANCEL_REDIRECT_URL: process.env.PROD_PADDLE_CANCEL_REDIRECT_URL,
  PADDLE_PUBLIC_KEY: process.env.PROD_PADDLE_PUBLIC_KEY,
  PADDLE_SECRET_KEY: process.env.PROD_PADDLE_SECRET_KEY,
  PADDLE_ENVIRONMENT: process.env.PROD_PADDLE_ENVIRONMENT,
  PADDLE_API_KEY: process.env.PROD_PADDLE_API_KEY,
  ONBOARDING_BASE_URL:
    process.env.PROD_ONBOARDING_BASE_URL ||
    "https://analytics.airqo.net/onboarding",
  ANALYTICS_PII_ENABLED:
    process.env.PROD_ANALYTICS_PII_ENABLED === "true" || false,
  POSTHOG_ENABLED: process.env.PROD_POSTHOG_ENABLED === "true" || false,
  POSTHOG_TRACK_API_REQUESTS:
    process.env.PROD_POSTHOG_TRACK_API_REQUESTS === "true" || false,
  GITHUB_CLIENT_ID: process.env.PROD_GITHUB_CLIENT_ID,
  GITHUB_CLIENT_SECRET: process.env.PROD_GITHUB_CLIENT_SECRET,
  LINKEDIN_CLIENT_ID: process.env.PROD_LINKEDIN_CLIENT_ID,
  LINKEDIN_CLIENT_SECRET: process.env.PROD_LINKEDIN_CLIENT_SECRET,
  MICROSOFT_CLIENT_ID: process.env.PROD_MICROSOFT_CLIENT_ID,
  MICROSOFT_CLIENT_SECRET: process.env.PROD_MICROSOFT_CLIENT_SECRET,
  TWITTER_CONSUMER_KEY: process.env.PROD_TWITTER_CONSUMER_KEY,
  TWITTER_CONSUMER_SECRET: process.env.PROD_TWITTER_CONSUMER_SECRET,
  TWITTER_BEARER_TOKEN: process.env.PROD_TWITTER_BEARER_TOKEN,

  REQUEST_ACCESS_EMAILS:
    process.env.PROD_REQUEST_ACCESS_EMAILS || process.env.REQUEST_ACCESS_EMAILS,
  COMMS_EMAILS: process.env.PROD_COMMS_EMAILS || process.env.COMMS_EMAILS,
  POLICY_EMAILS: process.env.PROD_POLICY_EMAILS || process.env.POLICY_EMAILS,
  CHAMPIONS_EMAILS:
    process.env.PROD_CHAMPIONS_EMAILS || process.env.CHAMPIONS_EMAILS,
  RESEARCHERS_EMAILS:
    process.env.PROD_RESEARCHERS_EMAILS || process.env.RESEARCHERS_EMAILS,
  ASSISTANCE_EMAILS:
    process.env.PROD_ASSISTANCE_EMAILS || process.env.ASSISTANCE_EMAILS,
  DEVELOPERS_EMAILS:
    process.env.PROD_DEVELOPERS_EMAILS || process.env.DEVELOPERS_EMAILS,
  PARTNERS_EMAILS:
    process.env.PROD_PARTNERS_EMAILS || process.env.PARTNERS_EMAILS,
  HARDWARE_AND_DS_EMAILS:
    process.env.PROD_HARDWARE_AND_DS_EMAILS ||
    process.env.HARDWARE_AND_DS_EMAILS,
  PLATFORM_AND_DS_EMAILS:
    process.env.PROD_PLATFORM_AND_DS_EMAILS ||
    process.env.PLATFORM_AND_DS_EMAILS,
  PLATFORM_EMAILS:
    process.env.PROD_PLATFORM_EMAILS || process.env.PLATFORM_EMAILS,
};
module.exports = prodConfig;
