const mongoose = require("mongoose");
const stageConfig = {
  ADMIN_SETUP_SECRET: process.env.STAGE_ADMIN_SETUP_SECRET,
  BYPASS_CAPTCHA: process.env.STAGE_BYPASS_CAPTCHA === "true" || false,
  RECAPTCHA_SITE_KEY: process.env.STAGE_RECAPTCHA_SITE_KEY,
  RECAPTCHA_SECRET_KEY: process.env.STAGE_RECAPTCHA_SECRET_KEY,
  BYPASS_RATE_LIMIT: process.env.STAGE_BYPASS_RATE_LIMIT === "true" || false,
  DEFAULT_AIRQLOUD: process.env.STAGE_DEFAULT_AIRQLOUD,
  DEFAULT_GRID: process.env.STAGE_DEFAULT_GRID,
  DEFAULT_GROUP: process.env.STAGE_DEFAULT_GROUP,
  AIRQO_GROUP_ID: process.env.STAGE_DEFAULT_GROUP,
  DEFAULT_GROUP_ROLE: process.env.STAGE_DEFAULT_GROUP_ROLE,
  DEFAULT_NETWORK: process.env.STAGE_DEFAULT_NETWORK,
  DEFAULT_NETWORK_ROLE: process.env.STAGE_DEFAULT_NETWORK_ROLE,
  MONGO_URI: process.env.MONGO_STAGE_URI,
  COMMAND_MONGO_URI: process.env.COMMAND_MONGO_STAGE_URI,
  QUERY_MONGO_URI: process.env.QUERY_MONGO_STAGE_URI,
  DB_NAME: process.env.MONGO_STAGE,
  PWD_RESET: `${process.env.ANALYTICS_STAGING_BASE_URL}/reset`,
  LOGIN_PAGE: `${process.env.ANALYTICS_STAGING_BASE_URL}/login`,
  FORGOT_PAGE: `${process.env.ANALYTICS_STAGING_BASE_URL}/forgot`,
  PLATFORM_BASE_URL: process.env.ANALYTICS_STAGING_BASE_URL,
  ANALYTICS_BASE_URL: "https://staging-analytics.airqo.net",
  ENVIRONMENT: "STAGING ENVIRONMENT",
  KAFKA_BOOTSTRAP_SERVERS: process.env.KAFKA_BOOTSTRAP_SERVERS_STAGE
    ? process.env.KAFKA_BOOTSTRAP_SERVERS_STAGE.split(",").filter(
        (value) => value.trim() !== ""
      )
    : [],
  KAFKA_TOPICS: process.env.KAFKA_TOPICS_STAGE,
  SCHEMA_REGISTRY: process.env.SCHEMA_REGISTRY_STAGE,
  KAFKA_RAW_MEASUREMENTS_TOPICS:
    process.env.KAFKA_RAW_MEASUREMENTS_TOPICS_STAGE,
  KAFKA_CLIENT_ID: process.env.KAFKA_CLIENT_ID_STAGE,
  KAFKA_CLIENT_GROUP: process.env.KAFKA_CLIENT_GROUP_STAGE,
  REDIS_SERVER: process.env.STAGE_REDIS_SERVER,
  REDIS_PORT: process.env.STAGE_REDIS_PORT,
  SELECTED_SITES: process.env.SELECTED_SITES_STAGING
    ? process.env.SELECTED_SITES_STAGING.split(",").filter(
        (value) => value.trim() !== ""
      )
    : [],
  API_TOKEN: process.env.STAGE_API_TOKEN,
  PADDLE_SUCCESS_REDIRECT_URL: process.env.STAGE_PADDLE_SUCCESS_REDIRECT_URL,
  PADDLE_CANCEL_REDIRECT_URL: process.env.STAGE_PADDLE_CANCEL_REDIRECT_URL,
  PADDLE_PUBLIC_KEY: process.env.STAGE_PADDLE_PUBLIC_KEY,
  PADDLE_SECRET_KEY: process.env.STAGE_PADDLE_SECRET_KEY,
  PADDLE_ENVIRONMENT: process.env.STAGE_PADDLE_ENVIRONMENT,
  PADDLE_API_KEY: process.env.STAGE_PADDLE_API_KEY,
  ONBOARDING_BASE_URL:
    process.env.STAGE_ONBOARDING_BASE_URL ||
    "https://staging-analytics.airqo.net/onboarding",
};

module.exports = stageConfig;
