const mongoose = require("mongoose");
const ObjectId = mongoose.Types.ObjectId;
const log4js = require("log4js");
const isEmpty = require("is-empty");
const { logObject, logText } = require("@utils/shared");
const logger = log4js.getLogger(`${this.ENVIRONMENT} -- constants-config`);

const devConfig = {
  PRECOMPUTE_ACTIVITIES_JOB_ENABLED:
    process.env.PRECOMPUTE_ACTIVITIES_JOB_ENABLED !== "false",
  API_TOKEN: process.env.DEV_API_TOKEN,
  API_BASE_URL: process.env.DEV_API_BASE_URL || "http://localhost:3000",
  DEFAULT_COHORT: process.env.DEV_DEFAULT_COHORT,
  MONGO_URI: process.env.MONGO_URI_DEV,
  COMMAND_MONGO_URI: process.env.COMMAND_MONGO_URI_DEV,
  QUERY_MONGO_URI: process.env.QUERY_MONGO_URI_DEV,
  DB_NAME: process.env.MONGO_DEV,
  REDIS_SERVER: process.env.REDIS_SERVER_DEV,
  REDIS_PORT: process.env.REDIS_PORT,
  KAFKA_BOOTSTRAP_SERVERS: process.env.KAFKA_BOOTSTRAP_SERVERS_DEV
    ? process.env.KAFKA_BOOTSTRAP_SERVERS_DEV.split(",").filter(
        (value) => value.trim() !== ""
      )
    : [],
  KAFKA_TOPICS: process.env.KAFKA_TOPICS_DEV,
  SCHEMA_REGISTRY: process.env.SCHEMA_REGISTRY_DEV,
  KAFKA_RAW_MEASUREMENTS_TOPICS: process.env.KAFKA_RAW_MEASUREMENTS_TOPICS_DEV,
  KAFKA_CLIENT_ID: process.env.KAFKA_CLIENT_ID_DEV,
  KAFKA_CLIENT_GROUP: process.env.KAFKA_CLIENT_GROUP_DEV,
  ENVIRONMENT: "DEVELOPMENT ENVIRONMENT",
  DATAWAREHOUSE_METADATA: process.env.DATAWAREHOUSE_METADATA_DEV,
  DATAWAREHOUSE_AVERAGED_DATA: process.env.DATAWAREHOUSE_AVERAGED_DATA_DEV,

  BIGQUERY_DEVICE_UPTIME_TABLE: process.env.DEV_BIGQUERY_DEVICE_UPTIME_TABLE,
  BIGQUERY_SITES: process.env.DEV_BIGQUERY_SITES,
  BIGQUERY_AIRQLOUDS_SITES: process.env.DEV_BIGQUERY_AIRQLOUDS_SITES,
  BIGQUERY_AIRQLOUDS: process.env.DEV_BIGQUERY_AIRQLOUDS,
  BIGQUERY_GRIDS_SITES: process.env.DEV_BIGQUERY_GRIDS_SITES,
  BIGQUERY_GRIDS: process.env.DEV_BIGQUERY_GRIDS,
  BIGQUERY_COHORTS_DEVICES: process.env.DEV_BIGQUERY_COHORTS_DEVICES,
  BIGQUERY_COHORTS: process.env.DEV_BIGQUERY_COHORTS,
  BIGQUERY_RAW_DATA: process.env.DEV_BIGQUERY_RAW_DATA,
  BIGQUERY_HOURLY_DATA: process.env.DEV_BIGQUERY_HOURLY_DATA,
  BIGQUERY_DEVICES: process.env.DEV_BIGQUERY_DEVICES,
  BIGQUERY_DEVICE_UPTIME_TABLE: process.env.DEV_BIGQUERY_DEVICE_UPTIME_TABLE,
  AUTH_SERVICE_URL: process.env.DEV_AUTH_SERVICE_URL,
  INTER_SERVICE_TOKEN: process.env.DEV_INTER_SERVICE_TOKEN,
  ADMIN_MIGRATION_KEY: process.env.DEV_ADMIN_MIGRATION_KEY,
  DEPLOYMENT_URL: process.env.DEV_DEPLOYMENT_URL,
  SERVICE_JWT_TOKEN: process.env.DEV_SERVICE_JWT_TOKEN,
};
module.exports = devConfig;
