# Generated by Django 4.2.16 on 2024-10-19 15:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cleanair', '0002_alter_forumevent_committee_text_section_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='authored_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cleanair_program_authored_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
