import os
from pathlib import Path

from dotenv import load_dotenv


BASE_DIR = Path(__file__).resolve().parent
dotenv_path = os.path.join(BASE_DIR, ".env")
load_dotenv(dotenv_path)


class Config:
    BOOTSTRAP_SERVERS = os.getenv("BOOTSTRAP_SERVERS").split(",")
    PURPLE_AIR_DATA_GROUP_ID = os.getenv("PURPLE_AIR_DATA_GROUP_ID")
    PURPLE_AIR_RAW_MEASUREMENTS_DATA_TOPIC = os.getenv(
        "PURPLE_AIR_RAW_MEASUREMENTS_DATA_TOPIC"
    )

    BIGQUERY_HOURLY_EVENTS_TABLE = os.getenv("BIGQUERY_HOURLY_EVENTS_TABLE")
    BIGQUERY_CALIBRATED_HOURLY_EVENTS_TABLE = os.getenv(
        "BIGQUERY_CALIBRATED_HOURLY_EVENTS_TABLE"
    )
    BIGQUERY_HOURLY_WEATHER_TABLE = os.getenv("BIGQUERY_HOURLY_WEATHER_TABLE")
    BIGQUERY_RAW_MOBILE_EVENTS_TABLE = os.getenv("BIGQUERY_RAW_MOBILE_EVENTS_TABLE")
    BIGQUERY_AIRQO_MOBILE_EVENTS_TABLE = os.getenv("BIGQUERY_AIRQO_MOBILE_EVENTS_TABLE")
    BIGQUERY_ANALYTICS_TABLE = os.getenv("BIGQUERY_ANALYTICS_TABLE")
    BIGQUERY_RAW_WEATHER_TABLE = os.getenv("BIGQUERY_RAW_WEATHER_TABLE")
    BIGQUERY_RAW_EVENTS_TABLE = os.getenv("BIGQUERY_RAW_EVENTS_TABLE")
    BIGQUERY_BAM_EVENTS_TABLE = os.getenv("BIGQUERY_BAM_EVENTS_TABLE")
    BIGQUERY_BAM_HOURLY_EVENTS_TABLE = os.getenv("BIGQUERY_BAM_HOURLY_EVENTS_TABLE")
    BIGQUERY_SITES_TABLE = os.getenv("BIGQUERY_SITES_TABLE")
    BIGQUERY_DEVICES_TABLE = os.getenv("BIGQUERY_DEVICES_TABLE")

    BIGQUERY_HOURLY_EVENTS_TABLE_SCHEMA = os.getenv(
        "BIGQUERY_HOURLY_EVENTS_TABLE_SCHEMA", "measurements.json"
    )
    BIGQUERY_HOURLY_WEATHER_TABLE_SCHEMA = os.getenv(
        "BIGQUERY_HOURLY_WEATHER_TABLE_SCHEMA", "weather_data.json"
    )
    BIGQUERY_ANALYTICS_TABLE_SCHEMA = os.getenv(
        "BIGQUERY_ANALYTICS_TABLE_SCHEMA", "data_warehouse.json"
    )

    WEATHER_MEASUREMENTS_TOPIC = os.getenv("WEATHER_MEASUREMENTS_TOPIC")
    INSIGHTS_MEASUREMENTS_TOPIC = os.getenv("INSIGHTS_MEASUREMENTS_TOPIC")
    HOURLY_MEASUREMENTS_TOPIC = os.getenv("HOURLY_MEASUREMENTS_TOPIC")
    BAM_MEASUREMENTS_TOPIC = os.getenv("BAM_MEASUREMENTS_TOPIC")

    AIRQO_BASE_URL = os.getenv("AIRQO_BASE_URL")
    CALIBRATION_BASE_URL = os.getenv("CALIBRATION_BASE_URL")
    AIRQO_BASE_URL_V2 = os.getenv("AIRQO_BASE_URL_V2")
    AIRQO_API_KEY = os.getenv("AIRQO_API_KEY")

    GOOGLE_APPLICATION_CREDENTIALS = os.getenv("GOOGLE_APPLICATION_CREDENTIALS")


configuration = Config()
