# Generated by Django 4.2.16 on 2024-10-19 17:00

import utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Press',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('article_title', models.CharField(max_length=100)),
                ('article_intro', models.CharField(
                    blank=True, max_length=200, null=True)),
                ('article_link', models.URLField(blank=True, null=True)),
                ('date_published', models.DateField()),
                ('publisher_logo', utils.fields.CustomImageField(
                    blank=True, default='uploads/default_image.webp', null=True, upload_to='uploads/images/')),
                ('order', models.IntegerField(default=1)),
                ('website_category', models.CharField(blank=True, choices=[
                 ('airqo', 'AirQo'), ('cleanair', 'CleanAir')], default='airqo', max_length=40, null=True)),
                ('article_tag', models.CharField(blank=True, choices=[
                 ('none', 'None'), ('featured', 'Featured')], default='none', max_length=40, null=True)),
            ],
            options={
                'verbose_name': 'Press Article',
                'verbose_name_plural': 'Press Articles',
                'ordering': ['order', '-id'],
            },
        ),
    ]
