# Generated by Django 4.2.16 on 2024-10-23 18:21

from django.db import migrations
import utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('press', '0004_alter_press_publisher_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='press',
            name='publisher_logo',
            field=utils.fields.CustomImageField(blank=True, default='uploads/default_image.webp', null=True, upload_to='uploads/images/'),
        ),
    ]
