# Generated by Django 4.2.5 on 2024-11-26 08:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('press', '0009_press_created_press_is_deleted_press_modified_and_more'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='press',
        #     name='created',
        #     field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 11, 26, 11, 46, 46, 495245)),
        #     preserve_default=False,
        # ),
        # migrations.AddField(
        #     model_name='press',
        #     name='is_deleted',
        #     field=models.BooleanField(default=False),
        # ),
        # migrations.AddField(
        #     model_name='press',
        #     name='modified',
        #     field=models.DateTimeField(auto_now=True),
        # ),
    ]
