# Generated by Django 4.2.5 on 2024-11-26 12:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('press', '0010_press_created_press_is_deleted_press_modified'),
    ]

    operations = [
        migrations.AddField(
            model_name='press',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 11, 26, 15, 15, 12, 175119)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='press',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='press',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
