# Generated by Django 4.2.5 on 2024-11-26 12:18

from django.db import migrations
import utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('press', '0011_press_created_press_is_deleted_press_modified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='press',
            name='publisher_logo',
            field=utils.fields.CustomImageField(blank=True, default='uploads/default_image.webp', null=True, upload_to='uploads/images/', validators=[utils.fields.validate_image_format]),
        ),
    ]
