# Generated by Django 5.1.4 on 2025-09-09 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('press', '0011_alter_press_publisher_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='press',
            name='slug',
            field=models.SlugField(blank=True, help_text='URL-friendly identifier', max_length=255, null=True, unique=True),
        ),
    ]
