app:
  name: airqo-stage-beacon-api
  label: sta-beacon-api
  azureSecret: sta-env-beacon
  k8sSecret: sta-beacon-api
  namespace: staging
replicaCount: 2
image:
  repository: airqoacr.azurecr.io/airqo-stage-beacon-api
  tag: stage-0e42150d-1773654341
resources:
  limits:
    cpu: 300m
    memory: 500Mi
  requests:
    cpu: 10m
    memory: 180Mi
volumeMounts:
  - name: config-volume
    mountPath: /etc/config
volumes:
  - name: config-volume
    configMap:
      name: beacon-config-files
ingress:
  enabled: false
service:
  type: NodePort
  port: 8000
  protocol: TCP
  targetPort: 8000
  nodePort: 31115
autoscaling:
  minReplicas: 1
  maxReplicas: 2
  targetMemoryUtilizationPercentage: 80
