# Generated by Django 4.2.16 on 2024-10-19 15:25

from django.db import migrations
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cleanair', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forumevent',
            name='committee_text_section',
            field=django_quill.fields.QuillField(blank=True, default='No details available yet.', null=True),
        ),
        migrations.AlterField(
            model_name='forumevent',
            name='glossary_details',
            field=django_quill.fields.QuillField(blank=True, default='No details available yet.', null=True),
        ),
        migrations.AlterField(
            model_name='forumevent',
            name='introduction',
            field=django_quill.fields.QuillField(blank=True, default='No details available yet.', null=True),
        ),
        migrations.AlterField(
            model_name='forumevent',
            name='partners_text_section',
            field=django_quill.fields.QuillField(blank=True, default='No details available yet.', null=True),
        ),
        migrations.AlterField(
            model_name='forumevent',
            name='registration_details',
            field=django_quill.fields.QuillField(blank=True, default='No details available yet.', null=True),
        ),
        migrations.AlterField(
            model_name='forumevent',
            name='schedule_details',
            field=django_quill.fields.QuillField(blank=True, default='No details available yet.', null=True),
        ),
        migrations.AlterField(
            model_name='forumevent',
            name='speakers_text_section',
            field=django_quill.fields.QuillField(blank=True, default='No details available yet.', null=True),
        ),
        migrations.AlterField(
            model_name='forumevent',
            name='sponsorship_opportunities_about',
            field=django_quill.fields.QuillField(blank=True, default='No details available yet.', null=True),
        ),
        migrations.AlterField(
            model_name='forumevent',
            name='sponsorship_opportunities_partners',
            field=django_quill.fields.QuillField(blank=True, default='No details available yet.', null=True),
        ),
        migrations.AlterField(
            model_name='forumevent',
            name='sponsorship_opportunities_schedule',
            field=django_quill.fields.QuillField(blank=True, default='No details available yet.', null=True),
        ),
        migrations.AlterField(
            model_name='forumevent',
            name='sponsorship_packages',
            field=django_quill.fields.QuillField(blank=True, default='No details available yet.', null=True),
        ),
        migrations.AlterField(
            model_name='forumevent',
            name='travel_logistics_accommodation_details',
            field=django_quill.fields.QuillField(blank=True, default='No details available yet.', null=True),
        ),
        migrations.AlterField(
            model_name='forumevent',
            name='travel_logistics_vaccination_details',
            field=django_quill.fields.QuillField(blank=True, default='No details available yet.', null=True),
        ),
        migrations.AlterField(
            model_name='forumevent',
            name='travel_logistics_visa_details',
            field=django_quill.fields.QuillField(blank=True, default='No details available yet.', null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='bio',
            field=django_quill.fields.QuillField(blank=True, default='No details available yet.', null=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='sub_text',
            field=django_quill.fields.QuillField(blank=True, default='No details available yet.', null=True),
        ),
    ]
