# Generated by Django 4.2.16 on 2024-10-19 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cleanair', '0004_forumevent_authored_by_partner_authored_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forumevent',
            name='authored_by',
        ),
    ]
