# Generated by Django 4.2.16 on 2024-10-23 18:21

from django.db import migrations
import utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cleanair', '0008_alter_cleanairresource_resource_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cleanairresource',
            name='resource_file',
            field=utils.fields.CustomFileField(blank=True, default='uploads/default_file.txt', null=True, upload_to='uploads/files/'),
        ),
        migrations.AlterField(
            model_name='forumevent',
            name='background_image',
            field=utils.fields.CustomImageField(blank=True, default='uploads/default_image.webp', null=True, upload_to='uploads/images/'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='partner_logo',
            field=utils.fields.CustomImageField(blank=True, default='uploads/default_image.webp', null=True, upload_to='uploads/images/'),
        ),
        migrations.AlterField(
            model_name='person',
            name='picture',
            field=utils.fields.CustomImageField(blank=True, default='uploads/default_image.webp', null=True, upload_to='uploads/images/'),
        ),
        migrations.AlterField(
            model_name='resourcefile',
            name='file',
            field=utils.fields.CustomFileField(blank=True, default='uploads/default_file.txt', null=True, upload_to='uploads/files/'),
        ),
    ]
