# Generated by Django 4.2.5 on 2024-11-25 23:14

import datetime
from django.db import migrations, models
import utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cleanair', '0012_alter_cleanairresource_resource_file_and_more'),
    ]

    operations = []
