# Generated by Django 4.2.5 on 2024-11-26 13:45

from django.db import migrations
import utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cleanair', '0013_cleanairresource_created_cleanairresource_is_deleted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cleanairresource',
            name='resource_file',
            field=utils.fields.CustomCloudinaryField(blank=True, default='website/uploads/default_image.webp', max_length=255, null=True, validators=[utils.fields.validate_image_format, utils.fields.validate_image_format]),
        ),
        migrations.AlterField(
            model_name='forumevent',
            name='background_image',
            field=utils.fields.CustomCloudinaryField(blank=True, default='website/uploads/default_image.webp', max_length=255, null=True, validators=[utils.fields.validate_image_format, utils.fields.validate_image_format]),
        ),
        migrations.AlterField(
            model_name='partner',
            name='partner_logo',
            field=utils.fields.CustomCloudinaryField(blank=True, default='website/uploads/default_image.webp', max_length=255, null=True, validators=[utils.fields.validate_image_format, utils.fields.validate_image_format]),
        ),
        migrations.AlterField(
            model_name='person',
            name='picture',
            field=utils.fields.CustomCloudinaryField(blank=True, default='website/uploads/default_image.webp', max_length=255, null=True, validators=[utils.fields.validate_image_format, utils.fields.validate_image_format]),
        ),
        migrations.AlterField(
            model_name='resourcefile',
            name='file',
            field=utils.fields.CustomCloudinaryField(blank=True, default='website/uploads/default_image.webp', max_length=255, null=True, validators=[utils.fields.validate_image_format, utils.fields.validate_image_format]),
        ),
    ]
