# Generated by Django 4.2.5 on 2024-11-26 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cleanair', '0014_add_basemodel_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='engagement',
            name='created',
            # Temporarily allow null
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='engagement',
            name='modified',
            # Temporarily allow null
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='engagement',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cleanairresource',
            name='created',
            # Temporarily allow null
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='cleanairresource',
            name='modified',
            # Temporarily allow null
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='cleanairresource',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='forumresource',
            name='created',
            # Temporarily allow null
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='forumresource',
            name='modified',
            # Temporarily allow null
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='forumresource',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='objective',
            name='created',
            # Temporarily allow null
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='objective',
            name='modified',
            # Temporarily allow null
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='objective',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='partner',
            name='created',
            # Temporarily allow null
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='partner',
            name='modified',
            # Temporarily allow null
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='partner',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='person',
            name='created',
            # Temporarily allow null
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='modified',
            # Temporarily allow null
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='program',
            name='created',
            # Temporarily allow null
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='modified',
            # Temporarily allow null
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='resourcefile',
            name='created',
            # Temporarily allow null
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='resourcefile',
            name='modified',
            # Temporarily allow null
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='resourcefile',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='resourcesession',
            name='created',
            # Temporarily allow null
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='resourcesession',
            name='modified',
            # Temporarily allow null
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='resourcesession',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='session',
            name='created',
            # Temporarily allow null
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='modified',
            # Temporarily allow null
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='support',
            name='created',
            # Temporarily allow null
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='support',
            name='modified',
            # Temporarily allow null
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='support',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
