# Generated by Django 5.1.4 on 2024-12-06 15:23

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cleanair', '0014_alter_cleanairresource_resource_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cleanairresource',
            name='resource_file',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='resource_file'),
        ),
        migrations.AlterField(
            model_name='forumevent',
            name='background_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='background_image'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='partner_logo',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='partner_logo'),
        ),
        migrations.AlterField(
            model_name='person',
            name='picture',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='picture'),
        ),
        migrations.AlterField(
            model_name='resourcefile',
            name='file',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='file'),
        ),
    ]
