# Generated by Django 5.1.4 on 2024-12-06 16:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cleanair', '0015_alter_cleanairresource_resource_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engagement',
            name='forum_event',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='engagement', to='cleanair.forumevent'),
        ),
        migrations.AlterField(
            model_name='session',
            name='session_details',
            field=models.TextField(default='No details available yet.'),
        ),
    ]
