# Generated by Django 4.2.5 on 2024-11-26 08:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cleanair', '0015_add_missing_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cleanairresource',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 11, 26, 11, 47, 1, 169576)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cleanairresource',
            name='modified',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2024, 11, 26, 11, 47, 5, 97967)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='engagement',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 11, 26, 11, 47, 7, 536153)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='engagement',
            name='modified',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2024, 11, 26, 11, 47, 9, 376813)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='forumevent',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 11, 26, 11, 47, 11, 257138)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='forumevent',
            name='modified',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2024, 11, 26, 11, 47, 13, 191151)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='forumresource',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 11, 26, 11, 47, 15, 225159)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='forumresource',
            name='modified',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2024, 11, 26, 11, 47, 17, 198913)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='objective',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 11, 26, 11, 47, 19, 126686)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='objective',
            name='modified',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2024, 11, 26, 11, 47, 21, 19677)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='partner',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 11, 26, 11, 47, 22, 655626)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='partner',
            name='modified',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2024, 11, 26, 11, 47, 24, 597770)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='person',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 11, 26, 11, 47, 26, 580832)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='person',
            name='modified',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2024, 11, 26, 11, 47, 28, 602926)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='program',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 11, 26, 11, 47, 30, 834450)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='program',
            name='modified',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2024, 11, 26, 11, 47, 32, 719139)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='resourcefile',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 11, 26, 11, 47, 35, 114863)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='resourcefile',
            name='modified',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2024, 11, 26, 11, 47, 37, 339623)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='resourcesession',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 11, 26, 11, 47, 39, 414875)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='resourcesession',
            name='modified',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2024, 11, 26, 11, 47, 41, 455006)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='session',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 11, 26, 11, 47, 43, 386564)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='session',
            name='modified',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2024, 11, 26, 11, 47, 46, 280685)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='support',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 11, 26, 11, 47, 48, 507836)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='support',
            name='modified',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2024, 11, 26, 11, 47, 50, 618768)),
            preserve_default=False,
        ),
    ]
