# Generated by Django 5.1.4 on 2025-02-06 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cleanair', '0018_remove_partner_forum_event_remove_person_forum_event_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partner',
            name='forum_events',
        ),
        migrations.RemoveField(
            model_name='person',
            name='forum_events',
        ),
        migrations.AddField(
            model_name='partner',
            name='forum_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partners', to='cleanair.forumevent'),
        ),
        migrations.AddField(
            model_name='person',
            name='forum_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='persons', to='cleanair.forumevent'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='category',
            field=models.CharField(choices=[('Funding Partner', 'FUNDING_PARTNER'), ('Host Partner', 'HOST_PARTNER'), ('Co-Convening Partner', 'CO_CONVENING_PARTNER'), ('Sponsor Partner', 'SPONSOR_PARTNER')], default='Funding Partner', max_length=50),
        ),
    ]
