# Generated by Django 5.1.4 on 2025-02-06 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cleanair', '0019_remove_partner_forum_events_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partner',
            name='forum_event',
        ),
        migrations.RemoveField(
            model_name='person',
            name='forum_event',
        ),
        migrations.AddField(
            model_name='partner',
            name='forum_events',
            field=models.ManyToManyField(blank=True, related_name='partners', to='cleanair.forumevent'),
        ),
        migrations.AddField(
            model_name='person',
            name='forum_events',
            field=models.ManyToManyField(blank=True, related_name='persons', to='cleanair.forumevent'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='category',
            field=models.CharField(choices=[('Funding Partner', 'FUNDING_PARTNER'), ('Host Partner', 'HOST_PARTNER'), ('Co-Convening Partner', 'CO_CONVENING_PARTNER'), ('Sponsor Partner', 'SPONSOR_PARTNER'), ('Program Partner', 'PROGRAM_PARTNER')], default='Funding Partner', max_length=50),
        ),
    ]
