# Generated by Django 5.1.4 on 2025-02-13 07:21

import django_quill.fields
import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cleanair', '0020_remove_partner_forum_event_remove_person_forum_event_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('content', django_quill.fields.QuillField(blank=True, default='', null=True)),
                ('section_type', models.CharField(choices=[('split', 'Split Section'), ('column', 'Column Section')], default='column', help_text='Select whether this is a split section (title on left, content on right) or a column section.', max_length=10)),
                ('reverse_order', models.BooleanField(default=False, help_text='If checked, the layout for a split section will be reversed (content on left, title on right).')),
                ('pages', multiselectfield.db.fields.MultiSelectField(choices=[('about', 'About Page'), ('committee', 'Committee Page'), ('session', 'Session Page'), ('speakers', 'Speakers Page'), ('partners', 'Partners Page'), ('sponsorships', 'Sponsorships Page'), ('logistics', 'Logistics Page'), ('glossary', 'Glossary Page')], default=['about'], help_text='Select the page(s) where this section should be displayed.', max_length=73)),
                ('order', models.IntegerField(default=1)),
                ('forum_events', models.ManyToManyField(related_name='sections', to='cleanair.forumevent')),
            ],
            options={
                'ordering': ['order', '-id'],
            },
        ),
    ]
