# Generated by Django 5.1.4 on 2025-02-13 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cleanair', '0021_section_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='forum_events',
            field=models.ManyToManyField(blank=True, related_name='sections', to='cleanair.forumevent'),
        ),
        migrations.AlterField(
            model_name='section',
            name='title',
            field=models.TextField(blank=True, help_text='Section title (optional)'),
        ),
    ]
