# Generated by Django 5.1.4 on 2025-05-22 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cleanair', '0023_alter_forumevent_unique_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='category',
            field=models.CharField(choices=[('Speaker', 'SPEAKER'), ('Committee Member', 'COMMITTEE_MEMBER'), ('Key Note Speaker', 'KEY_NOTE_SPEAKER'), ('Plenary Speaker', 'PLENARY_SPEAKER'), ('Speaker and Committee Member', 'SPEAKER_AND_COMMITTEE_MEMBER'), ('Committee Member and Key Note Speaker', 'COMMITTEE_MEMBER_AND_KEY_NOTE_SPEAKER'), ('Plenary and Committee Member', 'PLENARY_AND_COMMITTEE_MEMBER')], default='Speaker', max_length=50),
        ),
    ]
