# Generated by Django 5.1.4 on 2025-09-08 09:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cleanair', '0024_alter_person_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cleanairresource',
            options={'ordering': ['order', '-id'], 'verbose_name': 'Clean Air Resource', 'verbose_name_plural': 'Clean Air Resources'},
        ),
        migrations.AlterModelOptions(
            name='forumevent',
            options={'ordering': ['order', '-id'], 'verbose_name': 'Forum Event', 'verbose_name_plural': 'Clean Air Forum Events'},
        ),
        migrations.AlterField(
            model_name='resourcefile',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resource_files', to='cleanair.resourcesession'),
        ),
        migrations.AlterField(
            model_name='resourcesession',
            name='forum_resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resource_sessions', to='cleanair.forumresource'),
        ),
    ]
