# Generated by Django 5.1.4 on 2025-11-23 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cleanair', '0025_alter_cleanairresource_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cleanairresource',
            name='order',
            field=models.IntegerField(db_index=True, default=1),
        ),
        migrations.AlterField(
            model_name='forumevent',
            name='order',
            field=models.IntegerField(db_index=True, default=1),
        ),
        migrations.AlterField(
            model_name='forumresource',
            name='order',
            field=models.IntegerField(db_index=True, default=1),
        ),
        migrations.AlterField(
            model_name='partner',
            name='order',
            field=models.IntegerField(db_index=True, default=1),
        ),
        migrations.AlterField(
            model_name='person',
            name='order',
            field=models.IntegerField(db_index=True, default=1),
        ),
        migrations.AlterField(
            model_name='program',
            name='order',
            field=models.IntegerField(db_index=True, default=1),
        ),
        migrations.AlterField(
            model_name='resourcefile',
            name='order',
            field=models.IntegerField(db_index=True, default=1),
        ),
        migrations.AlterField(
            model_name='resourcesession',
            name='order',
            field=models.IntegerField(db_index=True, default=1),
        ),
        migrations.AlterField(
            model_name='section',
            name='order',
            field=models.IntegerField(db_index=True, default=1),
        ),
    ]
