# Inherit from the Python Docker image
FROM python:3.7-slim

# Copy the source code to app folder
COPY . /app/
# Change the working directory
WORKDIR /app/

# Install the Flask package via pip
RUN pip install -r requirements.txt
# Set "python" as the entry point
# Set environment variables
ENV ENV=staging

# Run the application
CMD ["python", "main.py", "--tenant=airqo"]