# Generated by Django 5.1.4 on 2025-09-18 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faqs', '0002_alter_faq_answer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faq',
            options={'ordering': ('order', '-created_at')},
        ),
        migrations.AddField(
            model_name='faq',
            name='order',
            field=models.IntegerField(default=1000, help_text='Lower values appear first'),
        ),
    ]
