# Generated by Django 5.1.4 on 2025-11-23 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faqs', '0003_alter_faq_options_faq_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='order',
            field=models.IntegerField(db_index=True, default=1000, help_text='Lower values appear first'),
        ),
    ]
