# Generated by Django 5.1.4 on 2025-12-02 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faqs', '0004_alter_faq_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='category',
            field=models.CharField(choices=[('general', 'General'), ('network', 'Network'), ('software', 'Software')], default='general', help_text='Category for the FAQ', max_length=20),
        ),
    ]
