# Generated by Django 5.1.4 on 2025-12-02 11:56

from django.db import migrations, models


def create_categories(apps, schema_editor):
    Category = apps.get_model('faqs', 'Category')
    Category.objects.get_or_create(name='General')
    Category.objects.get_or_create(name='Hardware')
    Category.objects.get_or_create(name='Software')


class Migration(migrations.Migration):

    dependencies = [
        ('faqs', '0005_faq_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.RunPython(create_categories),
        migrations.RemoveField(
            model_name='faq',
            name='category',
        ),
        migrations.AddField(
            model_name='faq',
            name='category',
            field=models.ForeignKey(default=1, on_delete=models.CASCADE, to='faqs.category'),
        ),
    ]
