# Generated by Django 5.1.4 on 2025-12-02 11:54

from django.db import migrations


def create_categories_and_migrate_faqs(apps, schema_editor):
    Category = apps.get_model('faqs', 'Category')
    FAQ = apps.get_model('faqs', 'FAQ')

    # Create categories
    general_cat, _ = Category.objects.get_or_create(name='General')
    hardware_cat, _ = Category.objects.get_or_create(name='Hardware')
    software_cat, _ = Category.objects.get_or_create(name='Software')

    # Update all FAQs to General category (since previous default was 'general')
    FAQ.objects.update(category=general_cat)


class Migration(migrations.Migration):

    dependencies = [
        ('faqs', '0006_category_alter_faq_category'),
    ]

    operations = [
        migrations.RunPython(create_categories_and_migrate_faqs),
    ]
