import environ
import json

env = environ.Env()
environ.Env.read_env()

# Security & Flask settings
SECRET_KEY = env("SUPERSET_SECRET_KEY")
FLASK_ENV = env("FLASK_ENV")

# Database Connection
SQLALCHEMY_DATABASE_URI = f"{env('DATABASE_DIALECT')}://{env('DATABASE_USER')}:{env('DATABASE_PASSWORD')}@{env('DATABASE_HOST')}:{env('DATABASE_PORT')}/{env('DATABASE_DB')}"
SQLALCHEMY_TRACK_MODIFICATIONS = False

# Web Server Settings
ENABLE_PROXY_FIX = env("SUPERSET_WEBSERVER_ENABLE_PROXY_FIX") == "True"
WEBSERVER_ADDRESS = env("SUPERSET_WEBSERVER_HOST")
WEBSERVER_PORT = env("SUPERSET_WEBSERVER_PORT")
SUPERSET_WEBSERVER_TIMEOUT = env("SUPERSET_WEBSERVER_TIMEOUT")

# Public URL
SUPERSET_PUBLIC_URL = env("SUPERSET_PUBLIC_URL")

# Cache Dict
CACHE_CONFIG = json.loads(env("CACHE_CONFIG"))

# Flask APP
FLASK_APP = env("FLASK_APP")
