apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.api.name }}
  labels:
    {{- include "airqo-analytics.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.api.label }}
  replicas: {{ .Values.api.replicaCount }}
  revisionHistoryLimit: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      {{- with .Values.api.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app: {{ .Values.api.label }}
    spec:
      containers:
        - name: {{ .Values.api.label }}
          image: "{{ .Values.images.repositories.api }}:{{ .Values.images.tag }}"
          imagePullPolicy: {{ default "IfNotPresent" .Values.images.pullPolicy }}
          ports:
            - containerPort: 5000
              name: {{ .Values.api.label }}
          envFrom:
            - secretRef:
                name: {{ .Values.api.secret }}
          volumeMounts:
            {{- toYaml .Values.volumeMounts | nindent 12 }}
          resources:
            limits:
              cpu: {{ .Values.api.resources.common.limits.cpu }}
              memory: {{ .Values.api.resources.common.limits.memory }}
            requests:
              cpu: {{ .Values.api.resources.common.requests.cpu }}
              memory: {{ .Values.api.resources.common.requests.memory }}
          livenessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 20
            periodSeconds: 30
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health/ready
              port: 5000
            initialDelaySeconds: 10
            periodSeconds: 15
            timeoutSeconds: 5
            failureThreshold: 3
      volumes:
        {{- toYaml .Values.volumes | nindent 8 }}

