{{- if .Values.externalSecret.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.api.secret }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: azure-kv-store
    kind: ClusterSecretStore
  target:
    name: {{ .Values.api.secret }}
    creationPolicy: Owner
    deletionPolicy: Retain
  dataFrom:
    - extract:
        key: {{ .Values.api.secret }}
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None

---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.jobs.reports.secret }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: azure-kv-store
    kind: ClusterSecretStore
  target:
    name: {{ .Values.jobs.reports.secret }}
    creationPolicy: Owner
    deletionPolicy: Retain
  dataFrom:
    - extract:
        key: {{ .Values.jobs.reports.secret }}
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
{{- end }}