{{- if .Values.externalSecret.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.api.secret }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: azure-kv-store
    kind: ClusterSecretStore
  target:
    name: {{ .Values.api.secret }}
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: {{ .Values.api.secret }}
        version: latest

---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.jobs.reports.secret }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: azure-kv-store
    kind: ClusterSecretStore
  target:
    name: {{ .Values.jobs.reports.secret }}
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: {{ .Values.jobs.reports.secret }}
        version: latest
{{- end }}