apiVersion: v1
kind: Service
metadata:
  name: '{{ .Values.api.name }}-svc'
  labels: {{- include "airqo-analytics.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    {{- range .Values.service.ports }}
    - name: {{ .name }}
      port: {{ .port }}
      targetPort: {{ .targetPort }}
      protocol: {{ .protocol }}
      {{- if and .nodePort (ne $.Values.service.type "ClusterIP") }}
      nodePort: {{ .nodePort }}
      {{- end }}
    {{- end }}
  selector:
    app: {{ .Values.api.label }}
