BASE_URL = '/api/v1'
ROOT = '/'
HEALTH_CHECK = '/health'
PARISHES = f'{BASE_URL}/locate/map/parishes'
CREATE_MAP = f'{BASE_URL}/locate/map/create'
GET_MAP = f'{BASE_URL}/locate/map/get'
UPDATE_MAP = f'{BASE_URL}/locate/map/update'
DELETE_MAP =  f'{BASE_URL}/map/delete'