"""add level to category

Revision ID: 0d5a7b8a17da
Revises: d44abd139eb1
Create Date: 2026-02-13 14:04:46.551508

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0d5a7b8a17da'
down_revision: Union[str, Sequence[str], None] = 'd44abd139eb1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category', sa.Column('level', sa.String(length=100), nullable=True))
    op.add_column('sync_metadata_values', sa.Column('field15', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sync_metadata_values', 'field15')
    op.drop_column('category', 'level')
    # ### end Alembic commands ###
