"""add_sync_device_performance_table

Revision ID: 13ddf260db82
Revises: 8663652ec8d3
Create Date: 2026-03-04 15:37:24.063240

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '13ddf260db82'
down_revision: Union[str, Sequence[str], None] = '8663652ec8d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sync_device_performance',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('device_id', sa.String(length=100), nullable=False),
    sa.Column('device_name', sa.String(length=200), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('last_active', sa.String(length=100), nullable=True),
    sa.Column('uptime', sa.Float(), nullable=False),
    sa.Column('data_completeness', sa.Float(), nullable=False),
    sa.Column('error_margin', sa.Float(), nullable=False),
    sa.Column('cohorts_json', sa.Text(), nullable=True),
    sa.Column('computed_for_date', sa.Date(), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('device_name', 'computed_for_date', name='uq_device_name_date')
    )
    op.create_index('ix_computed_for_date', 'sync_device_performance', ['computed_for_date'], unique=False)
    op.create_index(op.f('ix_sync_device_performance_device_name'), 'sync_device_performance', ['device_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sync_device_performance_device_name'), table_name='sync_device_performance')
    op.drop_index('ix_computed_for_date', table_name='sync_device_performance')
    op.drop_table('sync_device_performance')
    # ### end Alembic commands ###
