"""add_cohort_site_sync_tables

Revision ID: 1b049c103707
Revises: c1348ae3eeff
Create Date: 2026-04-22 20:41:57.027413

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '1b049c103707'
down_revision: Union[str, None] = 'c1348ae3eeff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sync_cohort',
    sa.Column('cohort_id', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('network', sa.String(length=100), nullable=True),
    sa.Column('visibility', sa.Boolean(), server_default='false', nullable=True),
    sa.Column('cohort_tags', sa.Text(), nullable=True),
    sa.Column('cohort_codes', sa.Text(), nullable=True),
    sa.Column('number_of_devices', sa.Integer(), server_default='0', nullable=True),
    sa.Column('platform_created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('cohort_id')
    )
    op.create_index(op.f('ix_sync_cohort_name'), 'sync_cohort', ['name'], unique=False)
    op.create_table('sync_site',
    sa.Column('site_id', sa.String(length=100), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('network', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('county', sa.String(length=100), nullable=True),
    sa.Column('district', sa.String(length=100), nullable=True),
    sa.Column('region', sa.String(length=100), nullable=True),
    sa.Column('data_provider', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('generated_name', sa.String(length=100), nullable=True),
    sa.Column('site_tags', sa.Text(), nullable=True),
    sa.Column('site_codes', sa.Text(), nullable=True),
    sa.Column('platform_created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('site_id')
    )
    op.create_index(op.f('ix_sync_site_name'), 'sync_site', ['name'], unique=False)
    op.create_table('sync_cohort_device',
    sa.Column('cohort_id', sa.String(length=100), nullable=False),
    sa.Column('device_id', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='false', nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['cohort_id'], ['sync_cohort.cohort_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['device_id'], ['sync_device.device_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('cohort_id', 'device_id')
    )
    op.create_table('sync_site_device',
    sa.Column('site_id', sa.String(length=100), nullable=False),
    sa.Column('device_id', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='false', nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['sync_device.device_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['site_id'], ['sync_site.site_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('site_id', 'device_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sync_site_device')
    op.drop_table('sync_cohort_device')
    op.drop_index(op.f('ix_sync_site_name'), table_name='sync_site')
    op.drop_table('sync_site')
    op.drop_index(op.f('ix_sync_cohort_name'), table_name='sync_cohort')
    op.drop_table('sync_cohort')
    # ### end Alembic commands ###
