"""add grids

Revision ID: 3410806a12d5
Revises: e5f8d03a2b1c
Create Date: 2026-05-07 22:42:53.789989

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '3410806a12d5'
down_revision: Union[str, None] = 'e5f8d03a2b1c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sync_grid',
    sa.Column('grid_id', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('visibility', sa.Boolean(), server_default='false', nullable=True),
    sa.Column('admin_level', sa.String(length=100), nullable=True),
    sa.Column('network', sa.String(length=100), nullable=True),
    sa.Column('long_name', sa.String(length=255), nullable=True),
    sa.Column('flag_url', sa.String(length=255), nullable=True),
    sa.Column('platform_created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('grid_id')
    )
    op.create_index(op.f('ix_sync_grid_name'), 'sync_grid', ['name'], unique=False)
    op.create_table('sync_grid_site',
    sa.Column('grid_id', sa.String(length=100), nullable=False),
    sa.Column('site_id', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='false', nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['grid_id'], ['sync_grid.grid_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['site_id'], ['sync_site.site_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('grid_id', 'site_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sync_grid_site')
    op.drop_index(op.f('ix_sync_grid_name'), table_name='sync_grid')
    op.drop_table('sync_grid')
    # ### end Alembic commands ###
