"""initial schema

Revision ID: 89c5f5806bd4
Revises: 
Create Date: 2026-03-26 15:58:17.047294

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '89c5f5806bd4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('level', sa.String(length=100), nullable=True),
    sa.Column('description', sa.String(length=100), nullable=True),
    sa.Column('field1', sa.String(length=100), nullable=True),
    sa.Column('field2', sa.String(length=100), nullable=True),
    sa.Column('field3', sa.String(length=100), nullable=True),
    sa.Column('field4', sa.String(length=100), nullable=True),
    sa.Column('field5', sa.String(length=100), nullable=True),
    sa.Column('field6', sa.String(length=100), nullable=True),
    sa.Column('field7', sa.String(length=100), nullable=True),
    sa.Column('field8', sa.String(length=100), nullable=True),
    sa.Column('field9', sa.String(length=100), nullable=True),
    sa.Column('field10', sa.String(length=100), nullable=True),
    sa.Column('field11', sa.String(length=100), nullable=True),
    sa.Column('field12', sa.String(length=100), nullable=True),
    sa.Column('field13', sa.String(length=100), nullable=True),
    sa.Column('field14', sa.String(length=100), nullable=True),
    sa.Column('field15', sa.String(length=100), nullable=True),
    sa.Column('metadata1', sa.String(length=100), nullable=True),
    sa.Column('metadata2', sa.String(length=100), nullable=True),
    sa.Column('metadata3', sa.String(length=100), nullable=True),
    sa.Column('metadata4', sa.String(length=100), nullable=True),
    sa.Column('metadata5', sa.String(length=100), nullable=True),
    sa.Column('metadata6', sa.String(length=100), nullable=True),
    sa.Column('metadata7', sa.String(length=100), nullable=True),
    sa.Column('metadata8', sa.String(length=100), nullable=True),
    sa.Column('metadata9', sa.String(length=100), nullable=True),
    sa.Column('metadata10', sa.String(length=100), nullable=True),
    sa.Column('metadata11', sa.String(length=100), nullable=True),
    sa.Column('metadata12', sa.String(length=100), nullable=True),
    sa.Column('metadata13', sa.String(length=100), nullable=True),
    sa.Column('metadata14', sa.String(length=100), nullable=True),
    sa.Column('metadata15', sa.String(length=100), nullable=True),
    sa.Column('config1', sa.String(length=100), nullable=True),
    sa.Column('config2', sa.String(length=100), nullable=True),
    sa.Column('config3', sa.String(length=100), nullable=True),
    sa.Column('config4', sa.String(length=100), nullable=True),
    sa.Column('config5', sa.String(length=100), nullable=True),
    sa.Column('config6', sa.String(length=100), nullable=True),
    sa.Column('config7', sa.String(length=100), nullable=True),
    sa.Column('config8', sa.String(length=100), nullable=True),
    sa.Column('config9', sa.String(length=100), nullable=True),
    sa.Column('config10', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('sync_device',
    sa.Column('device_id', sa.String(length=100), nullable=False),
    sa.Column('network_id', sa.String(length=100), nullable=True),
    sa.Column('current_firmware', sa.String(length=100), nullable=True),
    sa.Column('previous_firmware', sa.String(length=100), nullable=True),
    sa.Column('target_firmware', sa.String(length=100), nullable=True),
    sa.Column('file_upload_state', sa.Boolean(), server_default='false', nullable=True),
    sa.Column('firmware_download_state', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('device_id')
    )
    op.create_table('sync_device_performance',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('device_id', sa.String(length=100), nullable=False),
    sa.Column('device_name', sa.String(length=200), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('last_active', sa.String(length=100), nullable=True),
    sa.Column('uptime', sa.Float(), nullable=False),
    sa.Column('data_completeness', sa.Float(), nullable=False),
    sa.Column('error_margin', sa.Float(), nullable=False),
    sa.Column('cohorts_json', sa.Text(), nullable=True),
    sa.Column('complete_performance', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('computed_for_date', sa.Date(), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('device_name', 'computed_for_date', name='uq_device_name_date')
    )
    op.create_index('ix_computed_for_date', 'sync_device_performance', ['computed_for_date'], unique=False)
    op.create_index(op.f('ix_sync_device_performance_device_name'), 'sync_device_performance', ['device_name'], unique=False)
    op.create_table('sync_items_stock',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('stock', sa.Integer(), server_default='0', nullable=False),
    sa.Column('unit', sa.Text(), nullable=False),
    sa.Column('created_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint("name IS NOT NULL AND trim(name) != ''", name='chk_items_stock_name_not_empty'),
    sa.CheckConstraint("unit IS NOT NULL AND trim(unit) != ''", name='chk_items_stock_unit_not_empty'),
    sa.CheckConstraint('stock >= 0', name='chk_items_stock_stock'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sync_config_values',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('device_id', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('config1', sa.String(length=100), nullable=True),
    sa.Column('config2', sa.String(length=100), nullable=True),
    sa.Column('config3', sa.String(length=100), nullable=True),
    sa.Column('config4', sa.String(length=100), nullable=True),
    sa.Column('config5', sa.String(length=100), nullable=True),
    sa.Column('config6', sa.String(length=100), nullable=True),
    sa.Column('config7', sa.String(length=100), nullable=True),
    sa.Column('config8', sa.String(length=100), nullable=True),
    sa.Column('config9', sa.String(length=100), nullable=True),
    sa.Column('config10', sa.String(length=100), nullable=True),
    sa.Column('config_updated', sa.Boolean(), server_default='false', nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['sync_device.device_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sync_items_stock_history',
    sa.Column('history_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('item_id', sa.UUID(), nullable=False),
    sa.Column('old_stock', sa.Integer(), nullable=True),
    sa.Column('new_stock', sa.Integer(), nullable=False),
    sa.Column('old_unit', sa.Text(), nullable=True),
    sa.Column('new_unit', sa.Text(), nullable=False),
    sa.Column('change_type', sa.String(length=20), nullable=False),
    sa.Column('changed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint("(old_unit IS NULL OR trim(old_unit) != '') AND (new_unit IS NOT NULL AND trim(new_unit) != '')", name='chk_items_stock_history_unit_not_empty'),
    sa.CheckConstraint("change_type IN ('INSERT', 'STOCK_IN', 'STOCK_OUT', 'UNIT_CHANGE', 'DELETE')", name='chk_items_stock_history_change_type'),
    sa.CheckConstraint('(old_stock IS NULL OR old_stock >= 0) AND (new_stock >= 0)', name='chk_items_stock_history_stock_values'),
    sa.ForeignKeyConstraint(['item_id'], ['sync_items_stock.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('history_id')
    )
    op.create_table('sync_metadata_values',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('device_id', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('metadata1', sa.String(length=100), nullable=True),
    sa.Column('metadata2', sa.String(length=100), nullable=True),
    sa.Column('metadata3', sa.String(length=100), nullable=True),
    sa.Column('metadata4', sa.String(length=100), nullable=True),
    sa.Column('metadata5', sa.String(length=100), nullable=True),
    sa.Column('metadata6', sa.String(length=100), nullable=True),
    sa.Column('metadata7', sa.String(length=100), nullable=True),
    sa.Column('metadata8', sa.String(length=100), nullable=True),
    sa.Column('metadata9', sa.String(length=100), nullable=True),
    sa.Column('metadata10', sa.String(length=100), nullable=True),
    sa.Column('metadata11', sa.String(length=100), nullable=True),
    sa.Column('metadata12', sa.String(length=100), nullable=True),
    sa.Column('metadata13', sa.String(length=100), nullable=True),
    sa.Column('metadata14', sa.String(length=100), nullable=True),
    sa.Column('metadata15', sa.String(length=100), nullable=True),
    sa.Column('field15', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['sync_device.device_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sync_metadata_values')
    op.drop_table('sync_items_stock_history')
    op.drop_table('sync_config_values')
    op.drop_table('sync_items_stock')
    op.drop_index(op.f('ix_sync_device_performance_device_name'), table_name='sync_device_performance')
    op.drop_index('ix_computed_for_date', table_name='sync_device_performance')
    op.drop_table('sync_device_performance')
    op.drop_table('sync_device')
    op.drop_table('category')
    # ### end Alembic commands ###
