"""remove dim_device and update foreign keys

Revision ID: a0eb9498e93d
Revises: 0d5a7b8a17da
Create Date: 2026-02-13 14:17:31.775639

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a0eb9498e93d'
down_revision: Union[str, Sequence[str], None] = '0d5a7b8a17da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('sync_config_values_device_id_fkey', 'sync_config_values', type_='foreignkey')
    op.create_foreign_key('sync_config_values_device_id_fkey', 'sync_config_values', 'sync_device', ['device_id'], ['device_id'], ondelete='CASCADE')
    op.drop_constraint('sync_metadata_values_device_id_fkey', 'sync_metadata_values', type_='foreignkey')
    op.create_foreign_key('sync_metadata_values_device_id_fkey', 'sync_metadata_values', 'sync_device', ['device_id'], ['device_id'], ondelete='CASCADE')
    # op.drop_table('dim_device')  # Postponed/Skipped due to dependencies from other tables
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_table('dim_device', ... ) # dim_device was not dropped in upgrade
    op.drop_constraint('sync_metadata_values_device_id_fkey', 'sync_metadata_values', type_='foreignkey')
    op.create_foreign_key('sync_metadata_values_device_id_fkey', 'sync_metadata_values', 'dim_device', ['device_id'], ['device_id'], ondelete='CASCADE')
    op.drop_constraint('sync_config_values_device_id_fkey', 'sync_config_values', type_='foreignkey')
    op.create_foreign_key('sync_config_values_device_id_fkey', 'sync_config_values', 'dim_device', ['device_id'], ['device_id'], ondelete='CASCADE')
    # ### end Alembic commands ###
