"""add_inlab_batch_tables

Revision ID: a3d0ced5c059
Revises: fe1be7bd352d
Create Date: 2026-05-01 17:11:36.059976

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'a3d0ced5c059'
down_revision: Union[str, None] = 'fe1be7bd352d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sync_inlab_batch',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sync_inlab_batch_name'), 'sync_inlab_batch', ['name'], unique=True)
    op.create_table('sync_inlab_batch_device',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('batch_id', sa.UUID(), nullable=False),
    sa.Column('device_id', sa.String(length=100), nullable=False),
    sa.Column('firmware_version', sa.String(length=100), nullable=True),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_removed', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['batch_id'], ['sync_inlab_batch.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['device_id'], ['sync_device.device_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sync_inlab_batch_device_batch_id'), 'sync_inlab_batch_device', ['batch_id'], unique=False)
    op.create_index(op.f('ix_sync_inlab_batch_device_device_id'), 'sync_inlab_batch_device', ['device_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sync_inlab_batch_device_device_id'), table_name='sync_inlab_batch_device')
    op.drop_index(op.f('ix_sync_inlab_batch_device_batch_id'), table_name='sync_inlab_batch_device')
    op.drop_table('sync_inlab_batch_device')
    op.drop_index(op.f('ix_sync_inlab_batch_name'), table_name='sync_inlab_batch')
    op.drop_table('sync_inlab_batch')
    # ### end Alembic commands ###
