"""Add items stock tables

Revision ID: b39071ac13b5
Revises: 6aeb206c46ab
Create Date: 2026-02-13 13:16:42.044155

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b39071ac13b5'
down_revision: Union[str, Sequence[str], None] = '6aeb206c46ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sync_items_stock',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('stock', sa.Integer(), server_default='0', nullable=False),
    sa.Column('unit', sa.Text(), nullable=False),
    sa.Column('created_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint("name IS NOT NULL AND trim(name) != ''", name='chk_items_stock_name_not_empty'),
    sa.CheckConstraint("unit IS NOT NULL AND trim(unit) != ''", name='chk_items_stock_unit_not_empty'),
    sa.CheckConstraint('stock >= 0', name='chk_items_stock_stock'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sync_items_stock_history',
    sa.Column('history_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('item_id', sa.UUID(), nullable=False),
    sa.Column('old_stock', sa.Integer(), nullable=True),
    sa.Column('new_stock', sa.Integer(), nullable=False),
    sa.Column('old_unit', sa.Text(), nullable=True),
    sa.Column('new_unit', sa.Text(), nullable=False),
    sa.Column('change_type', sa.String(length=20), nullable=False),
    sa.Column('changed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint("(old_unit IS NULL OR trim(old_unit) != '') AND (new_unit IS NOT NULL AND trim(new_unit) != '')", name='chk_items_stock_history_unit_not_empty'),
    sa.CheckConstraint("change_type IN ('INSERT', 'STOCK_IN', 'STOCK_OUT', 'UNIT_CHANGE', 'DELETE')", name='chk_items_stock_history_change_type'),
    sa.CheckConstraint('(old_stock IS NULL OR old_stock >= 0) AND (new_stock >= 0)', name='chk_items_stock_history_stock_values'),
    sa.ForeignKeyConstraint(['item_id'], ['sync_items_stock.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('history_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sync_items_stock_history')
    op.drop_table('sync_items_stock')
    # ### end Alembic commands ###
