"""Add device number and keys to sync_device table

Revision ID: bf1cc73e3186
Revises: 63e90283a822
Create Date: 2026-04-06 17:26:49.460220

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'bf1cc73e3186'
down_revision: Union[str, None] = '63e90283a822'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sync_device', sa.Column('device_number', sa.Integer(), nullable=True))
    op.add_column('sync_device', sa.Column('writeKey', sa.String(length=100), nullable=True))
    op.add_column('sync_device', sa.Column('readKey', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sync_device', 'readKey')
    op.drop_column('sync_device', 'writeKey')
    op.drop_column('sync_device', 'device_number')
    # ### end Alembic commands ###
