"""Add index to metadata and config device_id

Revision ID: d8cfb6f957fa
Revises: 89c5f5806bd4
Create Date: 2026-03-26 17:49:12.947638

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd8cfb6f957fa'
down_revision: Union[str, None] = '89c5f5806bd4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_sync_config_values_device_id'), 'sync_config_values', ['device_id'], unique=False)
    op.create_index(op.f('ix_sync_metadata_values_device_id'), 'sync_metadata_values', ['device_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sync_metadata_values_device_id'), table_name='sync_metadata_values')
    op.drop_index(op.f('ix_sync_config_values_device_id'), table_name='sync_config_values')
    # ### end Alembic commands ###
