"""add_status_to_sync_device

Revision ID: e5f8d03a2b1c
Revises: d4e7c92f1a85
Create Date: 2026-05-07 18:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'e5f8d03a2b1c'
down_revision: Union[str, None] = 'd4e7c92f1a85'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sync_device', sa.Column('status', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sync_device', 'status')
    # ### end Alembic commands ###
