"""add_complete_performance_column

Revision ID: ed53bde08572
Revises: 13ddf260db82
Create Date: 2026-03-04 15:58:53.251879

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed53bde08572'
down_revision: Union[str, Sequence[str], None] = '13ddf260db82'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sync_device_performance', sa.Column('complete_performance', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sync_device_performance', 'complete_performance')
    # ### end Alembic commands ###
