"""add_thingspeak_data_sync_tables

Revision ID: fe1be7bd352d
Revises: 1b049c103707
Create Date: 2026-04-22 21:37:07.700606

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'fe1be7bd352d'
down_revision: Union[str, None] = '1b049c103707'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sync_daily_device_data',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('channel_id', sa.String(length=50), nullable=False),
    sa.Column('device_id', sa.String(length=100), nullable=True),
    sa.Column('data_date', sa.Date(), nullable=False),
    sa.Column('field1_avg', sa.Float(), nullable=True),
    sa.Column('field2_avg', sa.Float(), nullable=True),
    sa.Column('field3_avg', sa.Float(), nullable=True),
    sa.Column('field4_avg', sa.Float(), nullable=True),
    sa.Column('field5_avg', sa.Float(), nullable=True),
    sa.Column('field6_avg', sa.Float(), nullable=True),
    sa.Column('field7_avg', sa.Float(), nullable=True),
    sa.Column('field8_avg', sa.Float(), nullable=True),
    sa.Column('field9_avg', sa.Float(), nullable=True),
    sa.Column('field10_avg', sa.Float(), nullable=True),
    sa.Column('field11_avg', sa.Float(), nullable=True),
    sa.Column('field12_avg', sa.Float(), nullable=True),
    sa.Column('field13_avg', sa.Float(), nullable=True),
    sa.Column('field14_avg', sa.Float(), nullable=True),
    sa.Column('field15_avg', sa.Float(), nullable=True),
    sa.Column('field16_avg', sa.Float(), nullable=True),
    sa.Column('field17_avg', sa.Float(), nullable=True),
    sa.Column('field18_avg', sa.Float(), nullable=True),
    sa.Column('field19_avg', sa.Float(), nullable=True),
    sa.Column('field20_avg', sa.Float(), nullable=True),
    sa.Column('record_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('complete', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('synced_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('channel_id', 'data_date', name='uq_daily_channel_date')
    )
    op.create_index('ix_daily_channel_date', 'sync_daily_device_data', ['channel_id', 'data_date'], unique=False)
    op.create_index(op.f('ix_sync_daily_device_data_channel_id'), 'sync_daily_device_data', ['channel_id'], unique=False)
    op.create_table('sync_hourly_device_data',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('channel_id', sa.String(length=50), nullable=False),
    sa.Column('device_id', sa.String(length=100), nullable=True),
    sa.Column('hour_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('field1_avg', sa.Float(), nullable=True),
    sa.Column('field2_avg', sa.Float(), nullable=True),
    sa.Column('field3_avg', sa.Float(), nullable=True),
    sa.Column('field4_avg', sa.Float(), nullable=True),
    sa.Column('field5_avg', sa.Float(), nullable=True),
    sa.Column('field6_avg', sa.Float(), nullable=True),
    sa.Column('field7_avg', sa.Float(), nullable=True),
    sa.Column('field8_avg', sa.Float(), nullable=True),
    sa.Column('field9_avg', sa.Float(), nullable=True),
    sa.Column('field10_avg', sa.Float(), nullable=True),
    sa.Column('field11_avg', sa.Float(), nullable=True),
    sa.Column('field12_avg', sa.Float(), nullable=True),
    sa.Column('field13_avg', sa.Float(), nullable=True),
    sa.Column('field14_avg', sa.Float(), nullable=True),
    sa.Column('field15_avg', sa.Float(), nullable=True),
    sa.Column('field16_avg', sa.Float(), nullable=True),
    sa.Column('field17_avg', sa.Float(), nullable=True),
    sa.Column('field18_avg', sa.Float(), nullable=True),
    sa.Column('field19_avg', sa.Float(), nullable=True),
    sa.Column('field20_avg', sa.Float(), nullable=True),
    sa.Column('record_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('complete', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('synced_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('channel_id', 'hour_start', name='uq_hourly_channel_hour')
    )
    op.create_index('ix_hourly_channel_hour', 'sync_hourly_device_data', ['channel_id', 'hour_start'], unique=False)
    op.create_index(op.f('ix_sync_hourly_device_data_channel_id'), 'sync_hourly_device_data', ['channel_id'], unique=False)
    op.create_table('sync_raw_device_data',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('channel_id', sa.String(length=50), nullable=False),
    sa.Column('device_id', sa.String(length=100), nullable=True),
    sa.Column('entry_id', sa.Integer(), nullable=False),
    sa.Column('created_at_ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('field1', sa.Float(), nullable=True),
    sa.Column('field2', sa.Float(), nullable=True),
    sa.Column('field3', sa.Float(), nullable=True),
    sa.Column('field4', sa.Float(), nullable=True),
    sa.Column('field5', sa.Float(), nullable=True),
    sa.Column('field6', sa.Float(), nullable=True),
    sa.Column('field7', sa.Float(), nullable=True),
    sa.Column('field8', sa.Float(), nullable=True),
    sa.Column('field9', sa.Float(), nullable=True),
    sa.Column('field10', sa.Float(), nullable=True),
    sa.Column('field11', sa.Float(), nullable=True),
    sa.Column('field12', sa.Float(), nullable=True),
    sa.Column('field13', sa.Float(), nullable=True),
    sa.Column('field14', sa.Float(), nullable=True),
    sa.Column('field15', sa.Float(), nullable=True),
    sa.Column('field16', sa.Float(), nullable=True),
    sa.Column('field17', sa.Float(), nullable=True),
    sa.Column('field18', sa.Float(), nullable=True),
    sa.Column('field19', sa.Float(), nullable=True),
    sa.Column('field20', sa.Float(), nullable=True),
    sa.Column('synced_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('channel_id', 'entry_id', name='uq_raw_channel_entry')
    )
    op.create_index('ix_raw_channel_created', 'sync_raw_device_data', ['channel_id', 'created_at_ts'], unique=False)
    op.create_index(op.f('ix_sync_raw_device_data_channel_id'), 'sync_raw_device_data', ['channel_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sync_raw_device_data_channel_id'), table_name='sync_raw_device_data')
    op.drop_index('ix_raw_channel_created', table_name='sync_raw_device_data')
    op.drop_table('sync_raw_device_data')
    op.drop_index(op.f('ix_sync_hourly_device_data_channel_id'), table_name='sync_hourly_device_data')
    op.drop_index('ix_hourly_channel_hour', table_name='sync_hourly_device_data')
    op.drop_table('sync_hourly_device_data')
    op.drop_index(op.f('ix_sync_daily_device_data_channel_id'), table_name='sync_daily_device_data')
    op.drop_index('ix_daily_channel_date', table_name='sync_daily_device_data')
    op.drop_table('sync_daily_device_data')
    # ### end Alembic commands ###
