# Generated by Django 4.2.5 on 2024-11-25 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('externalteams', '0001_initial'),
    ]

    operations = []
