# Generated by Django 4.2.5 on 2024-11-26 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('externalteams', '0002_externalteammember_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='externalteamMember',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=False),
        ),
        migrations.AddField(
            model_name='externalteamMember',
            name='modified',
            field=models.DateTimeField(auto_now=True, null=False),
        ),
        migrations.AddField(
            model_name='externalteamMember',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
