# Generated by Django 4.2.5 on 2024-11-26 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('externalteams', '0003_add_basemodel_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='externalteamMemberbiography',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=False),
        ),
        migrations.AddField(
            model_name='externalteamMemberbiography',
            name='modified',
            field=models.DateTimeField(auto_now=True, null=False),
        ),
        migrations.AddField(
            model_name='externalteamMemberbiography',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
