# Generated by Django 5.1.4 on 2025-11-23 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('externalteams', '0007_alter_externalteammember_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externalteammember',
            name='order',
            field=models.IntegerField(db_index=True, default=1),
        ),
        migrations.AlterField(
            model_name='externalteammemberbiography',
            name='order',
            field=models.IntegerField(db_index=True, default=1),
        ),
    ]
