// config/global/permissions.js
const PERMISSIONS = {
  // System & Admin
  SYSTEM_ADMIN: "SYSTEM_ADMIN",
  SUPER_ADMIN: "SUPER_ADMIN",
  DATABASE_ADMIN: "DATABASE_ADMIN",
  ADMIN_FULL_ACCESS: "ADMIN_FULL_ACCESS",
  SYSTEM_CONFIGURE: "SYSTEM_CONFIGURE",
  SYSTEM_MONITOR: "SYSTEM_MONITOR",

  // Organization & Group Management
  ORG_CREATE: "ORG_CREATE",
  ORG_VIEW: "ORG_VIEW",
  ORG_UPDATE: "ORG_UPDATE",
  ORG_DELETE: "ORG_DELETE",
  ORG_APPROVE: "ORG_APPROVE",
  ORG_REJECT: "ORG_REJECT",

  // Group Management
  GROUP_VIEW: "GROUP_VIEW",
  GROUP_CREATE: "GROUP_CREATE",
  GROUP_EDIT: "GROUP_EDIT",
  GROUP_DELETE: "GROUP_DELETE",
  GROUP_MANAGEMENT: "GROUP_MANAGEMENT",
  GROUP_SETTINGS: "GROUP_SETTINGS",

  // Network Management
  NETWORK_VIEW: "NETWORK_VIEW",
  NETWORK_CREATE: "NETWORK_CREATE",
  NETWORK_EDIT: "NETWORK_EDIT",
  NETWORK_DELETE: "NETWORK_DELETE",
  NETWORK_MANAGEMENT: "NETWORK_MANAGEMENT",

  // User & Member Management
  USER_VIEW: "USER_VIEW",
  USER_CREATE: "USER_CREATE",
  USER_EDIT: "USER_EDIT",
  USER_DELETE: "USER_DELETE",
  USER_MANAGEMENT: "USER_MANAGEMENT",
  USER_INVITE: "USER_INVITE",
  MEMBER_VIEW: "MEMBER_VIEW",
  MEMBER_INVITE: "MEMBER_INVITE",
  MEMBER_REMOVE: "MEMBER_REMOVE",
  MEMBER_SEARCH: "MEMBER_SEARCH",
  MEMBER_EXPORT: "MEMBER_EXPORT",

  // Role & Permission Management
  ROLE_VIEW: "ROLE_VIEW",
  ROLE_CREATE: "ROLE_CREATE",
  ROLE_EDIT: "ROLE_EDIT",
  ROLE_DELETE: "ROLE_DELETE",
  ROLE_ASSIGNMENT: "ROLE_ASSIGNMENT",

  // Device Management
  DEVICE_VIEW: "DEVICE_VIEW",
  DEVICE_DEPLOY: "DEVICE_DEPLOY",
  DEVICE_RECALL: "DEVICE_RECALL",
  DEVICE_MAINTAIN: "DEVICE_MAINTAIN",
  DEVICE_UPDATE: "DEVICE_UPDATE",
  DEVICE_DELETE: "DEVICE_DELETE",
  DEVICE_CLAIM: "DEVICE_CLAIM",

  // Site Management
  SITE_VIEW: "SITE_VIEW",
  SITE_CREATE: "SITE_CREATE",
  SITE_UPDATE: "SITE_UPDATE",
  SITE_DELETE: "SITE_DELETE",

  // Dashboard & Analytics
  DASHBOARD_VIEW: "DASHBOARD_VIEW",
  ANALYTICS_VIEW: "ANALYTICS_VIEW",
  ANALYTICS_EXPORT: "ANALYTICS_EXPORT",
  DATA_VIEW: "DATA_VIEW",
  DATA_EXPORT: "DATA_EXPORT",
  DATA_COMPARE: "DATA_COMPARE",

  // Settings and Configuration
  SETTINGS_VIEW: "SETTINGS_VIEW",
  SETTINGS_EDIT: "SETTINGS_EDIT",

  // Content Management
  CONTENT_VIEW: "CONTENT_VIEW",
  CONTENT_CREATE: "CONTENT_CREATE",
  CONTENT_EDIT: "CONTENT_EDIT",
  CONTENT_DELETE: "CONTENT_DELETE",
  CONTENT_MODERATION: "CONTENT_MODERATION",

  // Audit & Reporting
  ACTIVITY_VIEW: "ACTIVITY_VIEW",
  AUDIT_VIEW: "AUDIT_VIEW",
  AUDIT_EXPORT: "AUDIT_EXPORT",
  REPORT_GENERATE: "REPORT_GENERATE",

  // API & Integration
  API_ACCESS: "API_ACCESS",
  TOKEN_GENERATE: "TOKEN_GENERATE",
  TOKEN_MANAGE: "TOKEN_MANAGE",
  TOKEN_ANALYZE: "TOKEN_ANALYZE",

  // Legacy Permissions (to be phased out)
  CREATE_UPDATE_AND_DELETE_NETWORK_DEVICES:
    "CREATE_UPDATE_AND_DELETE_NETWORK_DEVICES",
  CREATE_UPDATE_AND_DELETE_NETWORK_SITES:
    "CREATE_UPDATE_AND_DELETE_NETWORK_SITES",
  VIEW_AIR_QUALITY_FOR_NETWORK: "VIEW_AIR_QUALITY_FOR_NETWORK",
  CREATE_UPDATE_AND_DELETE_NETWORK_ROLES:
    "CREATE_UPDATE_AND_DELETE_NETWORK_ROLES",
  CREATE_UPDATE_AND_DELETE_NETWORK_USERS:
    "CREATE_UPDATE_AND_DELETE_NETWORK_USERS",
  MANAGE_NETWORK_SETTINGS: "MANAGE_NETWORK_SETTINGS",
  VIEW_NETWORK_DASHBOARD: "VIEW_NETWORK_DASHBOARD",
  CREATE_UPDATE_AND_DELETE_GROUP_DEVICES:
    "CREATE_UPDATE_AND_DELETE_GROUP_DEVICES",
  CREATE_UPDATE_AND_DELETE_GROUP_SITES: "CREATE_UPDATE_AND_DELETE_GROUP_SITES",
  VIEW_AIR_QUALITY_FOR_GROUP: "VIEW_AIR_QUALITY_FOR_GROUP",
  CREATE_UPDATE_AND_DELETE_GROUP_ROLES: "CREATE_UPDATE_AND_DELETE_GROUP_ROLES",
  CREATE_UPDATE_AND_DELETE_GROUP_USERS: "CREATE_UPDATE_AND_DELETE_GROUP_USERS",
  MANAGE_GROUP_SETTINGS: "MANAGE_GROUP_SETTINGS",
  VIEW_GROUP_DASHBOARD: "VIEW_GROUP_DASHBOARD",
  ACCESS_PLATFORM: "ACCESS_PLATFORM",
};

// Create a flat array of all permissions for easy iteration
PERMISSIONS.ALL = Object.values(PERMISSIONS).filter(
  (v) => typeof v === "string"
);

const DEFAULT_ROLE_DEFINITIONS = {
  AIRQO_SUPER_ADMIN: {
    role_name: "AIRQO_SUPER_ADMIN",
    role_code: "AIRQO_SUPER_ADMIN",
    role_description: "AirQo Super Administrator with all permissions",
    permissions: PERMISSIONS.ALL.filter(
      (p) =>
        ![
          "ACCESS_PLATFORM",
          "VIEW_AIR_QUALITY_FOR_GROUP",
          "VIEW_AIR_QUALITY_FOR_NETWORK",
        ].includes(p)
    ),
  },
  AIRQO_ADMIN: {
    role_name: "AIRQO_ADMIN",
    role_code: "AIRQO_ADMIN",
    role_description: "Default Administrator role for the AirQo organization",
    permissions: [
      PERMISSIONS.GROUP_VIEW,
      PERMISSIONS.GROUP_EDIT,
      PERMISSIONS.USER_MANAGEMENT,
      PERMISSIONS.MEMBER_VIEW,
      PERMISSIONS.MEMBER_INVITE,
      PERMISSIONS.MEMBER_REMOVE,
      PERMISSIONS.ROLE_VIEW,
      PERMISSIONS.SETTINGS_VIEW,
      PERMISSIONS.ANALYTICS_VIEW,
      PERMISSIONS.DEVICE_VIEW,
      PERMISSIONS.DEVICE_DEPLOY,
      PERMISSIONS.DEVICE_MAINTAIN,
      PERMISSIONS.SITE_VIEW,
      PERMISSIONS.DASHBOARD_VIEW,
      PERMISSIONS.DATA_VIEW,
      PERMISSIONS.DATA_EXPORT,
    ],
  },
  AIRQO_DEFAULT_USER: {
    role_name: "AIRQO_DEFAULT_USER",
    role_code: "AIRQO_DEFAULT_USER",
    role_description: "Default role for new AirQo users",
    permissions: [
      PERMISSIONS.DASHBOARD_VIEW,
      PERMISSIONS.DATA_VIEW,
      PERMISSIONS.ANALYTICS_VIEW,
      PERMISSIONS.DATA_EXPORT,
      PERMISSIONS.SITE_VIEW,
      PERMISSIONS.DEVICE_VIEW,
      PERMISSIONS.DEVICE_CLAIM,
      PERMISSIONS.DEVICE_DEPLOY,
      PERMISSIONS.NETWORK_VIEW,
      PERMISSIONS.API_ACCESS,
      PERMISSIONS.TOKEN_GENERATE,
    ],
  },
  DEFAULT_MEMBER: {
    role_name: "DEFAULT_MEMBER",
    role_code: "DEFAULT_MEMBER",
    role_description: "Default Member role for an organization",
    permissions: [
      PERMISSIONS.GROUP_VIEW,
      PERMISSIONS.MEMBER_VIEW,
      PERMISSIONS.DASHBOARD_VIEW,
      PERMISSIONS.DATA_VIEW,
      PERMISSIONS.DEVICE_VIEW,
      PERMISSIONS.SITE_VIEW,
    ],
  },
  TECHNICIAN: {
    role_name: "TECHNICIAN",
    role_code: "TECHNICIAN",
    role_description: "Technician role with device management permissions",
    permissions: [
      PERMISSIONS.GROUP_VIEW,
      PERMISSIONS.DEVICE_VIEW,
      PERMISSIONS.DEVICE_DEPLOY,
      PERMISSIONS.DEVICE_MAINTAIN,
      PERMISSIONS.SITE_VIEW,
      PERMISSIONS.DASHBOARD_VIEW,
      PERMISSIONS.DATA_VIEW,
      PERMISSIONS.MEMBER_VIEW,
    ],
  },
  ANALYST: {
    role_name: "ANALYST",
    role_code: "ANALYST",
    role_description: "Analyst role with data analysis permissions",
    permissions: [
      PERMISSIONS.GROUP_VIEW,
      PERMISSIONS.ANALYTICS_VIEW,
      PERMISSIONS.DASHBOARD_VIEW,
      PERMISSIONS.DATA_VIEW,
      PERMISSIONS.DATA_EXPORT,
      PERMISSIONS.DATA_COMPARE,
      PERMISSIONS.DEVICE_VIEW,
      PERMISSIONS.SITE_VIEW,
      PERMISSIONS.MEMBER_VIEW,
    ],
  },
  DEVELOPER: {
    role_name: "DEVELOPER",
    role_code: "DEVELOPER",
    role_description: "Developer role with API access permissions",
    permissions: [
      PERMISSIONS.GROUP_VIEW,
      PERMISSIONS.API_ACCESS,
      PERMISSIONS.TOKEN_GENERATE,
      PERMISSIONS.TOKEN_MANAGE,
      PERMISSIONS.DATA_VIEW,
      PERMISSIONS.DATA_EXPORT,
      PERMISSIONS.DEVICE_VIEW,
      PERMISSIONS.SITE_VIEW,
      PERMISSIONS.DASHBOARD_VIEW,
    ],
  },
  VIEWER: {
    role_name: "VIEWER",
    role_code: "VIEWER",
    role_description: "Viewer role with read-only access",
    permissions: [
      PERMISSIONS.GROUP_VIEW,
      PERMISSIONS.DEVICE_VIEW,
      PERMISSIONS.SITE_VIEW,
      PERMISSIONS.DASHBOARD_VIEW,
      PERMISSIONS.DATA_VIEW,
      PERMISSIONS.MEMBER_VIEW,
    ],
  },
};

PERMISSIONS.DEFAULTS = {
  SUPER_ADMIN: DEFAULT_ROLE_DEFINITIONS.AIRQO_SUPER_ADMIN.permissions,
  DEFAULT_ADMIN: DEFAULT_ROLE_DEFINITIONS.AIRQO_ADMIN.permissions,
  DEFAULT_USER: DEFAULT_ROLE_DEFINITIONS.AIRQO_DEFAULT_USER.permissions,
  DEFAULT_MEMBER: DEFAULT_ROLE_DEFINITIONS.DEFAULT_MEMBER.permissions,
};

PERMISSIONS.DEFAULT_ROLE_DEFINITIONS = DEFAULT_ROLE_DEFINITIONS;

PERMISSIONS.DEFAULT_NETWORK_MEMBER_PERMISSIONS = [
  PERMISSIONS.DASHBOARD_VIEW,
  PERMISSIONS.DATA_VIEW,
  PERMISSIONS.ANALYTICS_VIEW,
  PERMISSIONS.DATA_EXPORT,
  PERMISSIONS.SITE_VIEW,
  PERMISSIONS.DEVICE_VIEW,
  PERMISSIONS.DEVICE_CLAIM,
  PERMISSIONS.DEVICE_DEPLOY,
  PERMISSIONS.NETWORK_VIEW,
  PERMISSIONS.API_ACCESS,
  PERMISSIONS.TOKEN_GENERATE,
];

PERMISSIONS.DEFAULT_MEMBER_PERMISSIONS = [
  PERMISSIONS.GROUP_VIEW,
  PERMISSIONS.MEMBER_VIEW,
  PERMISSIONS.DASHBOARD_VIEW,
  PERMISSIONS.DATA_VIEW,
  PERMISSIONS.DEVICE_VIEW,
  PERMISSIONS.SITE_VIEW,
];

module.exports = PERMISSIONS;
