// config/global/permissions.js
module.exports = {
  // Organization request permissions
  ORG_REQUEST_PERMISSIONS: {
    LIST: "LIST_ORGANIZATION_REQUESTS",
    APPROVE: "APPROVE_ORGANIZATION_REQUEST",
    REJECT: "REJECT_ORGANIZATION_REQUEST",
    VIEW: "VIEW_ORGANIZATION_REQUEST",
  },

  // Group permissions
  GROUP_PERMISSIONS: {
    VIEW_DASHBOARD: "VIEW_GROUP_DASHBOARD",
    MANAGE_MEMBERS: "MANAGE_GROUP_MEMBERS",
    MANAGE_SETTINGS: "MANAGE_GROUP_SETTINGS",
    VIEW_MEMBERS: "VIEW_GROUP_MEMBERS",
  },
  DEFAULT_NETWORK_MEMBER_PERMISSIONS: ["READ_NETWORK", "UPDATE_NETWORK"],
};
