// config/global/permissions.js
const PERMISSIONS = {
  // System & Admin
  SYSTEM_ADMIN: "SYSTEM_ADMIN",
  SUPER_ADMIN: "SUPER_ADMIN",
  DATABASE_ADMIN: "DATABASE_ADMIN",
  ADMIN_FULL_ACCESS: "ADMIN_FULL_ACCESS",
  SYSTEM_CONFIGURE: "SYSTEM_CONFIGURE",
  SYSTEM_MONITOR: "SYSTEM_MONITOR",

  // Organization & Group Management
  ORG_CREATE: "ORG_CREATE",
  ORG_VIEW: "ORG_VIEW",
  ORG_UPDATE: "ORG_UPDATE",
  ORG_DELETE: "ORG_DELETE",
  ORG_APPROVE: "ORG_APPROVE",
  ORG_REJECT: "ORG_REJECT",

  // Group Management
  GROUP_VIEW: "GROUP_VIEW",
  GROUP_CREATE: "GROUP_CREATE",
  GROUP_EDIT: "GROUP_EDIT",
  GROUP_DELETE: "GROUP_DELETE",
  GROUP_MANAGEMENT: "GROUP_MANAGEMENT",
  GROUP_SETTINGS: "GROUP_SETTINGS",

  // Network Management
  NETWORK_VIEW: "NETWORK_VIEW",
  NETWORK_CREATE: "NETWORK_CREATE",
  NETWORK_EDIT: "NETWORK_EDIT",
  NETWORK_DELETE: "NETWORK_DELETE",
  NETWORK_MANAGEMENT: "NETWORK_MANAGEMENT",

  // User & Member Management
  USER_VIEW: "USER_VIEW",
  USER_CREATE: "USER_CREATE",
  USER_EDIT: "USER_EDIT",
  USER_DELETE: "USER_DELETE",
  USER_MANAGEMENT: "USER_MANAGEMENT",
  USER_INVITE: "USER_INVITE",
  MEMBER_VIEW: "MEMBER_VIEW",
  MEMBER_INVITE: "MEMBER_INVITE",
  MEMBER_REMOVE: "MEMBER_REMOVE",
  MEMBER_SEARCH: "MEMBER_SEARCH",
  MEMBER_EXPORT: "MEMBER_EXPORT",

  // Role & Permission Management
  ROLE_VIEW: "ROLE_VIEW",
  ROLE_CREATE: "ROLE_CREATE",
  ROLE_EDIT: "ROLE_EDIT",
  ROLE_DELETE: "ROLE_DELETE",
  ROLE_ASSIGNMENT: "ROLE_ASSIGNMENT",

  // Device Management
  DEVICE_VIEW: "DEVICE_VIEW",
  DEVICE_DEPLOY: "DEVICE_DEPLOY",
  DEVICE_RECALL: "DEVICE_RECALL",
  DEVICE_MAINTAIN: "DEVICE_MAINTAIN",
  DEVICE_UPDATE: "DEVICE_UPDATE",
  DEVICE_DELETE: "DEVICE_DELETE",
  DEVICE_CLAIM: "DEVICE_CLAIM",

  // Site Management
  SITE_VIEW: "SITE_VIEW",
  SITE_CREATE: "SITE_CREATE",
  SITE_UPDATE: "SITE_UPDATE",
  SITE_DELETE: "SITE_DELETE",

  // Dashboard & Analytics
  DASHBOARD_VIEW: "DASHBOARD_VIEW",
  ANALYTICS_VIEW: "ANALYTICS_VIEW",
  ANALYTICS_EXPORT: "ANALYTICS_EXPORT",
  DATA_VIEW: "DATA_VIEW",
  DATA_EXPORT: "DATA_EXPORT",
  DATA_COMPARE: "DATA_COMPARE",

  // Settings and Configuration
  SETTINGS_VIEW: "SETTINGS_VIEW",
  SETTINGS_EDIT: "SETTINGS_EDIT",

  // Content Management
  CONTENT_VIEW: "CONTENT_VIEW",
  CONTENT_CREATE: "CONTENT_CREATE",
  CONTENT_EDIT: "CONTENT_EDIT",
  CONTENT_DELETE: "CONTENT_DELETE",
  CONTENT_MODERATION: "CONTENT_MODERATION",

  // Audit & Reporting
  ACTIVITY_VIEW: "ACTIVITY_VIEW",
  AUDIT_VIEW: "AUDIT_VIEW",
  AUDIT_EXPORT: "AUDIT_EXPORT",
  REPORT_GENERATE: "REPORT_GENERATE",

  // API & Integration
  API_ACCESS: "API_ACCESS",
  TOKEN_GENERATE: "TOKEN_GENERATE",
  TOKEN_MANAGE: "TOKEN_MANAGE",
  TOKEN_ANALYZE: "TOKEN_ANALYZE",

  // Legacy Permissions (to be phased out)
  CREATE_UPDATE_AND_DELETE_NETWORK_DEVICES:
    "CREATE_UPDATE_AND_DELETE_NETWORK_DEVICES",
  CREATE_UPDATE_AND_DELETE_NETWORK_SITES:
    "CREATE_UPDATE_AND_DELETE_NETWORK_SITES",
  VIEW_AIR_QUALITY_FOR_NETWORK: "VIEW_AIR_QUALITY_FOR_NETWORK",
  CREATE_UPDATE_AND_DELETE_NETWORK_ROLES:
    "CREATE_UPDATE_AND_DELETE_NETWORK_ROLES",
  CREATE_UPDATE_AND_DELETE_NETWORK_USERS:
    "CREATE_UPDATE_AND_DELETE_NETWORK_USERS",
  MANAGE_NETWORK_SETTINGS: "MANAGE_NETWORK_SETTINGS",
  VIEW_NETWORK_DASHBOARD: "VIEW_NETWORK_DASHBOARD",
  CREATE_UPDATE_AND_DELETE_GROUP_DEVICES:
    "CREATE_UPDATE_AND_DELETE_GROUP_DEVICES",
  CREATE_UPDATE_AND_DELETE_GROUP_SITES: "CREATE_UPDATE_AND_DELETE_GROUP_SITES",
  VIEW_AIR_QUALITY_FOR_GROUP: "VIEW_AIR_QUALITY_FOR_GROUP",
  CREATE_UPDATE_AND_DELETE_GROUP_ROLES: "CREATE_UPDATE_AND_DELETE_GROUP_ROLES",
  CREATE_UPDATE_AND_DELETE_GROUP_USERS: "CREATE_UPDATE_AND_DELETE_GROUP_USERS",
  MANAGE_GROUP_SETTINGS: "MANAGE_GROUP_SETTINGS",
  VIEW_GROUP_DASHBOARD: "VIEW_GROUP_DASHBOARD",
  ACCESS_PLATFORM: "ACCESS_PLATFORM",
};

// Create a flat array of all permissions for easy iteration
PERMISSIONS.ALL = Object.values(PERMISSIONS).filter(
  (v) => typeof v === "string"
);

PERMISSIONS.DEFAULTS = {
  SUPER_ADMIN: [
    PERMISSIONS.SUPER_ADMIN,
    PERMISSIONS.SYSTEM_ADMIN,
    PERMISSIONS.DATABASE_ADMIN,
    PERMISSIONS.ORG_CREATE,
    PERMISSIONS.ORG_VIEW,
    PERMISSIONS.ORG_UPDATE,
    PERMISSIONS.ORG_DELETE,
    PERMISSIONS.ORG_APPROVE,
    PERMISSIONS.ORG_REJECT,
    PERMISSIONS.GROUP_MANAGEMENT,
    PERMISSIONS.USER_MANAGEMENT,
    PERMISSIONS.ROLE_ASSIGNMENT,
    PERMISSIONS.ROLE_VIEW,
    PERMISSIONS.MEMBER_VIEW,
    PERMISSIONS.MEMBER_INVITE,
    PERMISSIONS.MEMBER_REMOVE,
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.DATA_VIEW,
    PERMISSIONS.DATA_EXPORT,
    PERMISSIONS.SETTINGS_EDIT,
    PERMISSIONS.ANALYTICS_VIEW,
    PERMISSIONS.AUDIT_VIEW,
    PERMISSIONS.AUDIT_EXPORT,
    PERMISSIONS.DEVICE_VIEW,
    PERMISSIONS.DEVICE_DEPLOY,
    PERMISSIONS.DEVICE_RECALL,
    PERMISSIONS.DEVICE_MAINTAIN,
    PERMISSIONS.DEVICE_UPDATE,
    PERMISSIONS.DEVICE_DELETE,
    PERMISSIONS.SITE_VIEW,
    PERMISSIONS.SITE_CREATE,
    PERMISSIONS.SITE_UPDATE,
    PERMISSIONS.SITE_DELETE,
    PERMISSIONS.API_ACCESS,
    PERMISSIONS.TOKEN_GENERATE,
    PERMISSIONS.TOKEN_MANAGE,
    PERMISSIONS.NETWORK_MANAGEMENT,
  ],
  DEFAULT_ADMIN: [
    PERMISSIONS.GROUP_VIEW,
    PERMISSIONS.GROUP_EDIT,
    PERMISSIONS.USER_MANAGEMENT,
    PERMISSIONS.MEMBER_VIEW,
    PERMISSIONS.MEMBER_INVITE,
    PERMISSIONS.MEMBER_REMOVE,
    PERMISSIONS.ROLE_VIEW,
    PERMISSIONS.SETTINGS_VIEW,
    PERMISSIONS.ANALYTICS_VIEW,
    PERMISSIONS.DEVICE_VIEW,
    PERMISSIONS.DEVICE_DEPLOY,
    PERMISSIONS.DEVICE_MAINTAIN,
    PERMISSIONS.SITE_VIEW,
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.DATA_VIEW,
    PERMISSIONS.DATA_EXPORT,
  ],
  DEFAULT_USER: [
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.DATA_VIEW,
    PERMISSIONS.ANALYTICS_VIEW,
    PERMISSIONS.DATA_EXPORT,
    PERMISSIONS.SITE_VIEW,
    PERMISSIONS.DEVICE_VIEW,
    PERMISSIONS.DEVICE_CLAIM,
    PERMISSIONS.DEVICE_DEPLOY,
    PERMISSIONS.NETWORK_VIEW,
    PERMISSIONS.API_ACCESS,
    PERMISSIONS.TOKEN_GENERATE,
  ],
  DEFAULT_MEMBER: [
    PERMISSIONS.GROUP_VIEW,
    PERMISSIONS.MEMBER_VIEW,
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.DATA_VIEW,
    PERMISSIONS.DEVICE_VIEW,
    PERMISSIONS.SITE_VIEW,
  ],
};

module.exports = PERMISSIONS;
