apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.api.secret }}
  labels:
    {{- include "airqo-view-api.labels" . | nindent 4 }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: azure-kv-store   # your existing ClusterSecretStore
    kind: ClusterSecretStore
  target:
    name: {{ .Values.api.secret }}
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: {{ .Values.api.secret }} # key in external store
        version: latest
