# Generated by Django 5.1.4 on 2025-11-23 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0008_add_slug_support'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='order',
            field=models.IntegerField(db_index=True, default=1),
        ),
        migrations.AlterField(
            model_name='memberbiography',
            name='order',
            field=models.IntegerField(db_index=True, default=1),
        ),
    ]
