# Generated by Django 5.1.4 on 2026-03-04 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("team", "0009_alter_member_order_alter_memberbiography_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="category",
            field=models.CharField(
                choices=[("staff", "Staff"), ("fellow", "Fellow"), ("ex-fellow", "Ex-fellow")],
                db_index=True,
                default="staff",
                max_length=20,
            ),
        ),
    ]
