# Generated by Django 4.2.16 on 2024-10-19 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImpactNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('african_cities', models.IntegerField(default=8)),
                ('champions', models.IntegerField(default=1500)),
                ('deployed_monitors', models.IntegerField(default=200)),
                ('data_records', models.IntegerField(default=67)),
                ('research_papers', models.IntegerField(default=10)),
                ('partners', models.IntegerField(default=300)),
            ],
            options={
                'verbose_name': 'Impact Number',
                'verbose_name_plural': 'Impact Numbers',
            },
        ),
    ]
