# Generated by Django 4.2.5 on 2024-11-26 13:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='impactnumber',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 11, 26, 16, 44, 6, 587801)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='impactnumber',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='impactnumber',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
