# Generated by Django 4.2.16 on 2024-10-19 17:14

import utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Highlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=110)),
                ('image', utils.fields.CustomImageField(
                    blank=True, default='website/uploads/default_image.webp', null=True, upload_to='uploads/images/')),
                ('link', models.URLField()),
                ('link_title', models.CharField(blank=True, max_length=20)),
                ('order', models.IntegerField(default=1)),
                ('tags', models.ManyToManyField(
                    related_name='highlights', to='highlights.tag')),
            ],
            options={
                'ordering': ['order', '-id'],
            },
        ),
    ]
