# Generated by Django 4.2.5 on 2024-11-25 23:14

import datetime
from django.db import migrations, models
import utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('highlights', '0008_alter_highlight_image'),
    ]

    operations = []
