# Generated by Django 5.1.4 on 2025-11-23 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('highlights', '0013_alter_highlight_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='highlight',
            name='order',
            field=models.IntegerField(db_index=True, default=1),
        ),
    ]
