/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package airqo.models;
@org.apache.avro.specific.AvroGenerated
public enum tenant implements org.apache.avro.generic.GenericEnumSymbol<tenant> {
  airqo, kcca  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"tenant\",\"namespace\":\"airqo.models\",\"symbols\":[\"airqo\",\"kcca\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
