# Generated by Django 5.1.4 on 2026-05-04 09:26

import cloudinary.models
import django.utils.timezone
import django_quill.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BlogPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        help_text="URL-friendly identifier",
                        max_length=255,
                        null=True,
                        unique=True,
                    ),
                ),
                ("title", models.CharField(max_length=160)),
                ("summary", models.CharField(blank=True, default="", max_length=280)),
                ("content", django_quill.fields.QuillField(blank=True, default="")),
                (
                    "cover_image",
                    cloudinary.models.CloudinaryField(
                        blank=True,
                        default=None,
                        max_length=255,
                        null=True,
                        verbose_name="image",
                    ),
                ),
                (
                    "author_name",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                (
                    "published_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("is_published", models.BooleanField(db_index=True, default=True)),
                (
                    "website_category",
                    models.CharField(
                        blank=True,
                        choices=[("airqo", "AirQo"), ("cleanair", "CleanAir")],
                        db_index=True,
                        default="airqo",
                        max_length=40,
                        null=True,
                    ),
                ),
                ("order", models.IntegerField(db_index=True, default=1)),
            ],
            options={
                "verbose_name": "Blog Post",
                "verbose_name_plural": "Blog Posts",
                "ordering": ["order", "-published_at", "-id"],
                "abstract": False,
                "indexes": [
                    models.Index(
                        fields=["website_category", "is_published", "order"],
                        name="blog_blogpo_website_60aec1_idx",
                    ),
                    models.Index(
                        fields=["website_category", "is_published", "published_at"],
                        name="blog_blogpo_website_0f7a49_idx",
                    ),
                    models.Index(
                        fields=["is_published", "published_at"],
                        name="blog_blogpo_is_publ_dcd2a8_idx",
                    ),
                ],
            },
        ),
    ]
