# Generated by Django 5.1.4 on 2026-05-04 09:49

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpost",
            name="author_image",
            field=cloudinary.models.CloudinaryField(
                blank=True,
                default=None,
                max_length=255,
                null=True,
                verbose_name="image",
            ),
        ),
        migrations.AddField(
            model_name="blogpost",
            name="author_role",
            field=models.CharField(blank=True, default="", max_length=120),
        ),
        migrations.AddField(
            model_name="blogpost",
            name="meta_description",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="blogpost",
            name="meta_title",
            field=models.CharField(blank=True, default="", max_length=160),
        ),
    ]
