# Generated by Django 4.2.5 on 2024-11-25 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('externalteam', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externalteammember',
            name='title',
            field=models.CharField(max_length=120),
        ),
    ]
