# Generated by Django 4.2.16 on 2024-10-21 19:42

from django.db import migrations
import utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('externalTeam', '0002_alter_externalteammember_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externalteammember',
            name='picture',
            field=utils.fields.CustomImageField(blank=True, default='uploads/default_image.webp', null=True, upload_to='uploads/images/'),
        ),
    ]
