# Generated by Django 4.2.16 on 2024-10-26 14:17

from django.db import migrations
import utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('externalTeam', '0007_alter_externalteammember_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externalteammember',
            name='picture',
            field=utils.fields.CustomCloudinaryField(blank=True, default='website/uploads/default_image.webp', max_length=255, null=True),
        ),
    ]
