# Generated by Django 4.2.16 on 2024-10-23 18:29

from django.db import migrations, models
import django.db.models.deletion
import utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partner_image', utils.fields.CustomImageField(blank=True, default='uploads/default_image.webp', null=True, upload_to='uploads/images/')),
                ('partner_logo', utils.fields.CustomImageField(blank=True, default='uploads/default_image.webp', null=True, upload_to='uploads/images/')),
                ('partner_name', models.CharField(max_length=200)),
                ('order', models.IntegerField(default=1)),
                ('partner_link', models.URLField(blank=True, null=True)),
                ('type', models.CharField(blank=True, choices=[('partnership', 'Partnership'), ('collaboration', 'Collaboration'), ('policy', 'Policy'), ('funder', 'Funder'), ('research', 'Research'), ('ca-network', 'Clean air Network Partner'), ('ca-support', 'Clean air Supporting Partner'), ('ca-forum', 'Clean air Policy Forum'), ('ca-private-sector', 'Clean air Private Sector')], default='partnership', max_length=40, null=True)),
                ('website_category', models.CharField(blank=True, choices=[('airqo', 'AirQo'), ('cleanair', 'CleanAir')], default='airqo', max_length=40, null=True)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PartnerDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('order', models.IntegerField(default=1)),
                ('partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='descriptions', to='partners.partner')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
