# Generated by Django 4.2.16 on 2024-10-26 14:08

from django.db import migrations
import utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0002_alter_partner_partner_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='partner_image',
            field=utils.fields.CustomImageField(blank=True, default='uploads/default_image.webp', null=True, upload_to='uploads/images/'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='partner_logo',
            field=utils.fields.CustomImageField(blank=True, default='uploads/default_image.webp', null=True, upload_to='uploads/images/'),
        ),
    ]
