# Generated by Django 4.2.16 on 2024-10-26 14:17

from django.db import migrations
import utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0003_alter_partner_partner_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='partner_image',
            field=utils.fields.CustomCloudinaryField(blank=True, default='website/uploads/default_image.webp', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='partner',
            name='partner_logo',
            field=utils.fields.CustomCloudinaryField(blank=True, default='website/uploads/default_image.webp', max_length=255, null=True),
        ),
    ]
