# Generated by Django 4.2.5 on 2024-11-26 13:44

import datetime
from django.db import migrations, models
import utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0004_alter_partner_partner_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 11, 26, 16, 44, 9, 340141)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='partner',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='partner',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='partnerdescription',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 11, 26, 16, 44, 12, 576811)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='partnerdescription',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='partnerdescription',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='partner',
            name='partner_image',
            field=utils.fields.CustomCloudinaryField(blank=True, default='website/uploads/default_image.webp', max_length=255, null=True, validators=[utils.fields.validate_image_format, utils.fields.validate_image_format]),
        ),
        migrations.AlterField(
            model_name='partner',
            name='partner_logo',
            field=utils.fields.CustomCloudinaryField(blank=True, default='website/uploads/default_image.webp', max_length=255, null=True, validators=[utils.fields.validate_image_format, utils.fields.validate_image_format]),
        ),
    ]
