# Generated by Django 4.2.5 on 2024-11-26 08:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0005_partner_created_partner_is_deleted_partner_modified_and_more'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='partner',
        #     name='created',
        #     field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 11, 26, 11, 46, 42, 895346)),
        #     preserve_default=False,
        # ),
        # migrations.AddField(
        #     model_name='partner',
        #     name='is_deleted',
        #     field=models.BooleanField(default=False),
        # ),
        # migrations.AddField(
        #     model_name='partner',
        #     name='modified',
        #     field=models.DateTimeField(auto_now=True),
        # ),
        # migrations.AddField(
        #     model_name='partnerdescription',
        #     name='created',
        #     field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(
        #         2024, 11, 26, 11, 46, 44, 655129)),
        #     preserve_default=False,
        # ),
        # migrations.AddField(
        #     model_name='partnerdescription',
        #     name='is_deleted',
        #     field=models.BooleanField(default=False),
        # ),
        # migrations.AddField(
        #     model_name='partnerdescription',
        #     name='modified',
        #     field=models.DateTimeField(auto_now=True),
        # ),
    ]
