# Generated by Django 5.1.4 on 2025-10-28 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0008_add_slugs_to_partners'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
