# Generated by Django 5.1.4 on 2025-11-23 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0009_partner_featured'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='order',
            field=models.IntegerField(db_index=True, default=1),
        ),
        migrations.AlterField(
            model_name='partnerdescription',
            name='order',
            field=models.IntegerField(db_index=True, default=1),
        ),
    ]
