# Generated by Django 4.2.5 on 2024-11-26 08:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0002_bulletdescription_created_and_more'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='bulletdescription',
        #     name='created',
        #     field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 11, 26, 11, 33, 3, 714337)),
        #     preserve_default=False,
        # ),
        # migrations.AddField(
        #     model_name='bulletdescription',
        #     name='is_deleted',
        #     field=models.BooleanField(default=False),
        # ),
        # migrations.AddField(
        #     model_name='bulletdescription',
        #     name='modified',
        #     field=models.DateTimeField(auto_now=True),
        # ),
        # migrations.AddField(
        #     model_name='bulletpoint',
        #     name='created',
        #     field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 11, 26, 11, 33, 9, 641735)),
        #     preserve_default=False,
        # ),
        # migrations.AddField(
        #     model_name='bulletpoint',
        #     name='is_deleted',
        #     field=models.BooleanField(default=False),
        # ),
        # migrations.AddField(
        #     model_name='bulletpoint',
        #     name='modified',
        #     field=models.DateTimeField(auto_now=True),
        # ),
        # migrations.AddField(
        #     model_name='career',
        #     name='created',
        #     field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 11, 26, 11, 33, 11, 445309)),
        #     preserve_default=False,
        # ),
        # migrations.AddField(
        #     model_name='career',
        #     name='is_deleted',
        #     field=models.BooleanField(default=False),
        # ),
        # migrations.AddField(
        #     model_name='career',
        #     name='modified',
        #     field=models.DateTimeField(auto_now=True),
        # ),
        # migrations.AddField(
        #     model_name='department',
        #     name='created',
        #     field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 11, 26, 11, 33, 14, 138666)),
        #     preserve_default=False,
        # ),
        # migrations.AddField(
        #     model_name='department',
        #     name='is_deleted',
        #     field=models.BooleanField(default=False),
        # ),
        # migrations.AddField(
        #     model_name='department',
        #     name='modified',
        #     field=models.DateTimeField(auto_now=True),
        # ),
        # migrations.AddField(
        #     model_name='jobdescription',
        #     name='created',
        #     field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 11, 26, 11, 33, 15, 774630)),
        #     preserve_default=False,
        # ),
        # migrations.AddField(
        #     model_name='jobdescription',
        #     name='is_deleted',
        #     field=models.BooleanField(default=False),
        # ),
        # migrations.AddField(
        #     model_name='jobdescription',
        #     name='modified',
        #     field=models.DateTimeField(auto_now=True),
        # ),
    ]
