# Generated by Django 5.1.4 on 2025-11-23 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0003_add_slug_support'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulletdescription',
            name='order',
            field=models.IntegerField(db_index=True, default=1),
        ),
        migrations.AlterField(
            model_name='bulletpoint',
            name='order',
            field=models.IntegerField(db_index=True, default=1),
        ),
        migrations.AlterField(
            model_name='jobdescription',
            name='order',
            field=models.IntegerField(db_index=True, default=1),
        ),
    ]
