apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.app.secret }}
  namespace: {{ .Values.app.namespace }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: azure-kv-store
    kind: ClusterSecretStore
  target:
    name: {{ .Values.app.secret }}
    creationPolicy: Owner
    deletionPolicy: Retain
  dataFrom:
    - extract:
        key: {{ .Values.app.secret }}
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None