from setuptools import setup, find_packages

VERSION = "1.0.0"
DESCRIPTION = "AirQo Airflow custom python package"
LONG_DESCRIPTION = "This package contains functions shared by the DAG files"

setup(
    name="airqo_etl_utils",
    version=VERSION,
    author="AirQo",
    author_email="<data@airqo.net>",
    description=DESCRIPTION,
    long_description=LONG_DESCRIPTION,
    packages=find_packages(),
    package_data={"": ["*.json", "*.csv", "*.sql"]},
    install_requires=[
        "pandas==2.3.3",
        "requests==2.31.0",
        "simplejson==3.20.2",
        "numpy==1.24.4",
        "pyarrow==11.0.0",
        "python-dotenv==1.0.0",
        "google-cloud-bigquery==3.11.3",
        "google-cloud-storage==2.10.0",
        "google-cloud-bigquery-storage==2.22.0",
        "firebase-admin==6.9.0",
        "lightgbm==4.1.0",
        "mlflow==3.2.0",
        "gcsfs==2023.9.2",
        "pymongo==4.5.0",
        "optuna==4.8.0",
        "tweepy==4.16.0",
        "scikit-learn==1.2.2",
        "great_expectations==0.18.18",
        "airflow-provider-great-expectations==0.2.8",
        "apache-airflow-providers-google==10.2.0",
        "apache-airflow-providers-celery==3.17.2",
        "sqlalchemy-bigquery==1.11.0",
        "confluent-kafka==2.5.0",
        "lz4==4.3.3",
        "earthengine-api==1.7.19",
        "netCDF4==1.7.4",
        "cdsapi==0.7.4",
        "cfgrib==0.9.15.1",
        "xarray==2025.6.0",
        "python-dateutil==2.8.2",
        "azure-storage-blob==12.16.0",
        "azure-identity==1.13.0",
        "boto3==1.26.161",
        "google-api-python-client==2.92.0",
    ],
    keywords=["python", "airflow", "AirQo"],
    license="MIT",
    classifiers=[
        "Intended Audience :: AirQo Airflow Users",
        "Programming Language :: Python :: 3",
    ],
)
