from setuptools import setup, find_packages

VERSION = "1.0.0"
DESCRIPTION = "AirQo Airflow custom python package"
LONG_DESCRIPTION = "This package contains functions shared by the DAG files"

setup(
    name="airqo_etl_utils",
    version=VERSION,
    author="AirQo",
    author_email="<data@airqo.net>",
    description=DESCRIPTION,
    long_description=LONG_DESCRIPTION,
    packages=find_packages(),
    package_data={"": ["*.json", "*.csv", "*.sql"]},
    install_requires=[
        "pandas",
        "requests",
        "simplejson",
        "numpy",
        "pyarrow",
        "python-dotenv",
        "google-cloud-bigquery",
        "google-cloud-storage",
        "google-cloud-bigquery-storage",
        "firebase-admin",
        "lightgbm~=4.1.0",
        "mlflow",
        "gcsfs~=2023.9.2",
        "pymongo~=4.5.0",
        "optuna",
        "tweepy",
        "scikit-learn==1.2.2",
        "great_expectations===0.18.18",
        "airflow-provider-great-expectations==0.2.8",
        "apache-airflow-providers-google",
        "sqlalchemy-bigquery==1.11.0",
        "confluent-kafka==2.5.0",
        "lz4==4.3.3",
        "earthengine-api",
        "netCDF4",
        "cdsapi>=0.7.4",
        "cfgrib",
        "xarray==2025.6.0",
        "python-dateutil",
        "azure-storage-blob",
        "azure-identity",
        "boto3",
        "google-api-python-client",
    ],
    keywords=["python", "airflow", "AirQo"],
    license="MIT",
    classifiers=[
        "Intended Audience :: AirQo Airflow Users",
        "Programming Language :: Python :: 3",
    ],
)
