resource "google_bigquery_table" "darksky_weather_history_all_2019" {
  dataset_id  = "thingspeak"
  description = "Hourly weather data for the whole of 2019 by location ref,  generated from https://darksky.net/  API and cleaned using ...... on github. Includes a wide range of features generated by models"

  labels = {
    weather = "darksky"
  }

  project  = var.project-id
  schema   = "[{\"mode\":\"NULLABLE\",\"name\":\"int64_field_0\",\"type\":\"INTEGER\"},{\"mode\":\"NULLABLE\",\"name\":\"loc_ref\",\"type\":\"STRING\"},{\"mode\":\"NULLABLE\",\"name\":\"chan_ref\",\"type\":\"STRING\"},{\"mode\":\"NULLABLE\",\"name\":\"chan_id\",\"type\":\"INTEGER\"},{\"mode\":\"NULLABLE\",\"name\":\"latitude\",\"type\":\"FLOAT\"},{\"mode\":\"NULLABLE\",\"name\":\"longitude\",\"type\":\"FLOAT\"},{\"mode\":\"NULLABLE\",\"name\":\"time\",\"type\":\"TIMESTAMP\"},{\"mode\":\"NULLABLE\",\"name\":\"timezone\",\"type\":\"STRING\"},{\"mode\":\"NULLABLE\",\"name\":\"summary\",\"type\":\"STRING\"},{\"mode\":\"NULLABLE\",\"name\":\"temperature\",\"type\":\"FLOAT\"},{\"mode\":\"NULLABLE\",\"name\":\"apparentTemperature\",\"type\":\"FLOAT\"},{\"mode\":\"NULLABLE\",\"name\":\"humidity\",\"type\":\"FLOAT\"},{\"mode\":\"NULLABLE\",\"name\":\"pressure\",\"type\":\"FLOAT\"},{\"mode\":\"NULLABLE\",\"name\":\"visibility\",\"type\":\"FLOAT\"},{\"mode\":\"NULLABLE\",\"name\":\"windBearing\",\"type\":\"INTEGER\"},{\"mode\":\"NULLABLE\",\"name\":\"windGust\",\"type\":\"FLOAT\"},{\"mode\":\"NULLABLE\",\"name\":\"windSpeed\",\"type\":\"FLOAT\"},{\"mode\":\"NULLABLE\",\"name\":\"cloudCover\",\"type\":\"FLOAT\"},{\"mode\":\"NULLABLE\",\"name\":\"dewPoint\",\"type\":\"FLOAT\"},{\"mode\":\"NULLABLE\",\"name\":\"icon\",\"type\":\"STRING\"},{\"mode\":\"NULLABLE\",\"name\":\"ozone\",\"type\":\"FLOAT\"},{\"mode\":\"NULLABLE\",\"name\":\"precipType\",\"type\":\"STRING\"},{\"mode\":\"NULLABLE\",\"name\":\"precipIntensity\",\"type\":\"FLOAT\"},{\"mode\":\"NULLABLE\",\"name\":\"precipProbability\",\"type\":\"FLOAT\"},{\"mode\":\"NULLABLE\",\"name\":\"uvIndex\",\"type\":\"INTEGER\"}]"
  table_id = "darksky_weather_history_all_2019"
}
# terraform import google_bigquery_table.darksky_weather_history_all_2019 projects/${var.project-id}/datasets/thingspeak/tables/darksky_weather_history_all_2019
