app:
  name: workflows
  label: workflows
  secret: prod-env-airflow
  namespace: pipeline
  serviceAccount: airflow-sa
replicaCount: 2
images:
  repositories:
    initContainer: airqoacr.azurecr.io/airqo-workflows-xcom
    redisContainer: airqoacr.azurecr.io/airqo-redis
    containers: airqoacr.azurecr.io/airqo-workflows
  tag: prod-17043644-1775989165
nodeSelector:
  workload: airflow

tolerations:
  - key: "airflow"
    operator: "Equal"
    value: "true"
    effect: "NoSchedule"
resources:
  initContainer:
    requests:
      cpu: 50m
      memory: 32Mi
    limits:
      cpu: 250m
      memory: 80Mi
  webserver:
    requests:
      cpu: 125m
      memory: 1000Mi
    limits:
      cpu: 500m
      memory: 2000Mi
  scheduler:
    requests:
      cpu: 500m
      memory: 1000Mi
    limits:
      cpu: 1500m
      memory: 1800Mi
  celery:
    requests:
      cpu: 1000m
      memory: 2500Mi
    limits:
      cpu: 2000m
      memory: 3000Mi
  redis:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 300m
      memory: 256Mi
volumeMounts:
  - name: config-volume
    mountPath: /etc/config
  - name: xcom-config-volume
    mountPath: /etc/airflow_xcom
volumes:
  - name: config-volume
    configMap:
      name: airflow-config-files
  - name: xcom-config-volume
    emptyDir: {}
ingress:
  enabled: false
service:
  type: NodePort
  ports:
    - name: web-server
      port: 8080
      targetPort: 8080
      nodePort: 30036
      protocol: TCP
    - name: redis-server
      port: 6379
      targetPort: 6379
      nodePort: 30079
      protocol: TCP
autoscaling:
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 70
