# Generated by Django 4.2.16 on 2024-10-23 18:21

from django.db import migrations
import utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('africancities', '0004_alter_africancountry_country_flag_alter_image_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='africancountry',
            name='country_flag',
            field=utils.fields.CustomImageField(blank=True, default='uploads/default_image.webp', null=True, upload_to='uploads/images/'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=utils.fields.CustomImageField(blank=True, default='uploads/default_image.webp', null=True, upload_to='uploads/images/'),
        ),
    ]
