# Generated by Django 4.2.5 on 2024-11-25 23:14

import datetime
from django.db import migrations, models
import utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('africancities', '0008_alter_africancountry_country_flag_alter_image_image'),
    ]

    operations = []
