# Generated by Django 4.2.5 on 2024-11-26 12:18

from django.db import migrations
import utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('africancities', '0011_africancountry_created_africancountry_is_deleted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='africancountry',
            name='country_flag',
            field=utils.fields.CustomImageField(blank=True, default='uploads/default_image.webp', null=True, upload_to='uploads/images/', validators=[utils.fields.validate_image_format]),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=utils.fields.CustomImageField(blank=True, default='uploads/default_image.webp', null=True, upload_to='uploads/images/', validators=[utils.fields.validate_image_format]),
        ),
    ]
