# Generated by Django 5.1.4 on 2025-11-23 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('africancities', '0011_alter_africancountry_country_flag_alter_image_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='africancountry',
            name='order',
            field=models.IntegerField(db_index=True, default=1),
        ),
        migrations.AlterField(
            model_name='city',
            name='order',
            field=models.IntegerField(db_index=True, default=1),
        ),
        migrations.AlterField(
            model_name='content',
            name='order',
            field=models.IntegerField(db_index=True, default=1),
        ),
        migrations.AlterField(
            model_name='description',
            name='order',
            field=models.IntegerField(db_index=True, default=1),
        ),
        migrations.AlterField(
            model_name='image',
            name='order',
            field=models.IntegerField(db_index=True, default=1),
        ),
    ]
